import _ from 'lodash'

const questions = [{"text": "Welches der Medikamente ist ein Kalziumkanalblocker vom Dihydropyridin-Typ?",
"answers": ["Candesartan", "Amiodaron", "Amlodipin", "Carvedilol"]},
{"text": "Woher haben schwefelhaltige Leukotriene das Schwefel?",
"answers":["Sulfat",
"Gluthation",
"Serin",
"Cystin"]},
{"text": "Was zählt nicht zu den modifizierten Duke Kriterien",
"answers":["Herzinsuffizienz",
"positive Blutkulturen",
"positives Echo",
"septische Lungeninfarkte"]},
{"text": "Welche Tumore sind im hinteren Mediastinum am häufigsten?",
"answers":["Thymom",
"Schilddrüsentumor",
"Neurinom"]},
{"text": "eine 53 jährige Patientin klapt über Dyspnoe bereits bei Ersteigen einer Etage. Sie hätte keinen Husten oder Auswurf, führendes Symptom sie die seit 1 Jahr progrediente Bleastungsdyspnoe. In der Lungenfunktionsprüfung zeigt die Patientin weder eine obstruktive noch eine restriktive Lungenerkrankung, jeodch eine Einschränkung der Diffusionskapazität auf 48% des altersentsprechenen Sollwertes. Welche Diagnose ist am wahrscheinlichsten?",
"answers":["Belastungsinduziertes Asthma bronchiale",
"COPD im Anfangsstadium",
"idipathische pulmonale Fibrose",
"pulmonale Hypertonie"]},
{"text": "Welche Aussage zum Asthma Bronchiale bei Kindern im Schulalter trifft zu?",
"answers":["es handelt sich meistens um nicht-allergisches Asthma",
"Lungenfunktion in Ruhe meist normal",
"die Prävalenz beträgt 5-8 %",
"meist kommt es nicht zu einer Spontanremission"]},
{"text": "Behandlung von Persistierendem VH-Flimmern:",
"answers":["Antiarrhythmika",
"muss nicht therapiert werden, wenn länger als 1 Jahr andauernd"]},
{"text": "Welche Befunde in der Lungenfunktionsdiagnostik sind typisch für eine Lungenfibrose ?",
"answers":["FVC 70%, FEV1 95%, TLC 75 %, DLCO 50%",
"FVC 70%, FEV1 60%, TLC 120 %, DLCO 50%",
"FVC 100%, FEV1 95%, TLC 100 %, DLCO 100%",
"FVC 100%, FEV1 60%, TLC 100 %, DLCO 50%",
"FVC 100%, FEV1 95%, TLC 100 %, DLCO 50%"]},
{"text": "Welche Aussage stimmt ?",
"answers":["Bei Lungenemphysem ist das Residualvolumen vergrößert/erhöht",
"bei PAH ist DLCO nicht vermindert"]},
{"text": "Ein invasiv beatmeter 69-jähriger Patient auf einer Intensivstation hat bei einem Anteil von 50% Sauerstoff im Inspirationsgas eine an der Fingerbeere gemessene Sauerstoffsättigung von 79%. Welche Aussage zur Bewertung dieses Befundes trifft zu?",
"answers":["Eine Minderperfusion der Hand kann nicht die Ursache der erniedrigten Sauerstoffsättigung sein",
"Ein Pneumothorax ist als eine mögliche URsache für die erniedrifte Sauerstoffsättigung des Blutes ausgeschlossen",
"Eine Erhöhung der applizierten Sauerstoffkonzentration ist nicht indiziert",
"Ist ein akutes Lungenversagen nach der Berlin-Definition die Ursache für die erniedrigte Sauerstoffsättigung des Blutes, ist die Applikation von postiv end-exspiratorischem Atemwegsdruck (PEEP) indiziert"]},
{"text": "Welche Diagbnostik bei Herzinsuffizient:",
"answers":["EKG, Sono und Herzkatheter zum Ausschluss KHK",
"BNP messen",
"CT zur genauen Ermittlung der Herzgröße",
"MRT zur genauen Ermittlung der EF"]},
{"text": "Große Raumforderung im oberen Mediastinum, was kanns sein?",
"answers":["Terratom",
"Thymom",
"Lymphom"]},
{"text": "Was gibt man vorrangig bei einer exazerbierten COPD?",
"answers":["Amoxicillin - meint Frage ABTx der zu 80% auslösenden Inf.? Mittel der Wahl bei vorrangig verantwortlichen Keimen? Scheinbar lt. Skript W1 S2?",
"Formoterol",
"Sauerstoff",
"Salbutamol - Oder doch: Tx der Exazerbation *an sich*?",
"glaube eher Amoxicillin- entscheidend ist wahrscheinlich das \"vorrangig\", denn den Rest gibt man ja bei ner \"normalen\" auch und O2 bei Exazerbation auf jeden Fall auch"]},
{"text": "Wie hoch ist das Lebenszeitrisiko für eine Aortenruptur bei einem Aneurysma der Aorta descendens von 7cm Durchmesser?",
"answers":["5% (keine Angabe in den VL-Folien, Herold: Rupturrisiko von 7%/Jahr bei ≥ 6cm)",
"10%",
"20%",
"40%",
"80%",
"30%  (http://www.cardio-praxis-mh.de/v3/images/pdf/10taa2.pdf)",
"hier sind sogar >60% angegeben (S.4) http://www.gefaesschirurgie.de/fileadmin/websites/dgg/download/LL_Aneurysmen_Bauch_Becken_2011.pdf"]},
{"text": "Welche ist KEINE Kontraindikation für AT1-Antagonisten?",
"answers":["Schwangerschaft",
"Sick Sinus Syndrom",
"Nierenarterienstenose",
"Hypertrophe Kardiomyopathie",
"Herzplappenvitien",
"Niereninsuffizienz"]},
{"text": "Ein Patient mit schwerem Asthma kommt zu Ihnen in die Praxis zwecks Blutdruckeinstellung. Welches Medikament verschreiben Sie?",
"answers":["Metoprolol",
"Enalapril - Thiazid (das ist doch ein ACE Hemmer und damit ist Enalapril richtig oder?)",
"Carvediol",
"Amlodipin",
"ACE-Hemmer haben als häufige Nebenwirkung trockenen Reizhusten. Daher lieber zu vermeiden."]},
{"text": "Bei Vorhofflimmern, welche Blutverdünnung ausser Cumarinen?",
"answers":["ASS",
"Direkte Orale Antikoagulatien",
"Heparin (in der Akutsituation laut Amboss)",
"Paracetamol"]},
{"text": "Golden Standard zur TB-Diagnostik",
"answers":["Hauttest",
"Röntgen",
"Erregeranzucht",
"BAL mit Immunzytologie"]},
{"text": "Was bedeutet der PWC150?",
"answers":["die Herzfrequenz eines Patienten bei einer Ergometrie bei 150 Watt",
"die Watt-Zahl pro kg KG bei einer Ergometrie, wenn der Patient eine Herzfrequenz von 150 hat",
"Ein Quotient aus dem BMI und der Körperkerntemperatur",
"Bestandteil einer arbeitsmedizinischen Untersuchung zur Beurteilung von Feuerwehrmännern"]},
{"text": "Welche der genannten Krankheiten gehört zu den akut lebensbedrohlichen 6 der \"Deadly Dozen\" der Thoraxtraumatologie?",
"answers":["Herzkontusion",
"Diaphragmaruptur",
"Ösophagusruptur",
"Spannungspneumothorax"]},
{"text": "Was ist kein Risikofaktor für die Entwicklung einer KHK? (Nicht die exakte Formulierung aber vom Sinn her)",
"answers":["arterielle Hypertonie",
"Diabetes mellitus",
"Nikotinabusus",
"Alkoholabusus",
"Hypercholesterinämie"]},
{"text": "Welches der folgenden Aussagen trifft zu?",
"answers":["Bei einem Lungenemphysem ist das Residualvolumen der Lunge erhöht",
"bei ainer PAH bleibt die DCLO unverändert",
"Eine untherapierte PAH ist keiner Vorstufe einer Cor Pulmonale",
"SCLC ist der am langsam wachsender Bronchialkarzinom"]},
{"text": "Frau kann noch zwei Etagen Treppen steigen, bekommt dann Luftnot, welches NYHA-Stadium?",
"answers":["I",
"II",
"III",
"IV",
"V"]},
{"text": "Vier Tage nach stattgehabtem Myokardinfarkt hören Sie über Erb ein Holosystolikum. Wahrscheinlichste Ursache?",
"answers":["Mitralinsuffizient aufgrund eines Papillarmuskelabriss",
"Ventrikelseptumdefekt nach Infarkt",
"Perikarditis",
"Koronaraneurysma",
"rupturiertes Koronaraneurysma"]},
{"text": "EKG Zeichen eines STEMI ?",
"answers":["0,1 mv Hebung in allen Elektroden",
"0,2 mv Hebung in zwei benachbarten Elektroden",
"0,3 mv Hebung in allen Elektroden",
"0,2 mv Hebung in allen Elektroden",
"0,3 mv Hebung in zwei nicht benachbarten Elektroden"]},
{"text": "Welche Aussage über die Dissektion der Aorta ist richtig?",
"answers":["Bei einer akuten Dissektion der Aorta ist das D-Dimer erhöht",
"Bei einer akuten Dissektion der Aortaist die Magnetresonanztomographie die Bildgebung der Wahl",
"Bei einer akuten Dissektion der Aorta ascendens steigt die Mortalität jede Stunde um ca. 0,1%",
"Bei einer akuten Dissektion der Aorta ascendens ist eine sofortige Angiographie zur Darstellung der Koronarartien indiziert"]},
{"text": "Was versteht man unter einer pulmonalen Hypertonie und was ist deren häufigste Ursache?",
"answers":["erhöhter Druck im Lungenkreislauf (>25 mmHg) durch Rechtsherzversagen",
"erhöhter Druck im Lungenkreislauf (>25 mmHg) durch Linksherzinsuffizienz",
"erhöhter Druck im Lungenkreislauf (>25 mmHg) durch Erhöhung des präkapillaren Widerstandes",
"erhöhter Druck im Lungenkreislauf (>25 mmHg) durch rezidivierende Lungenembolien"]},
{"text": "Welche Aussage zu Bypass-Material trifft zu?",
"answers":["Die A. thoracica interna links hat von allen Bypass-Gefäßen die besten Langzeitergebnisse bezogen auf die Offenheitsrate",
"Arterielle Bypassgefäße haben weniger lange Offenheitsraten als venöse Bypassgefäße",
"venöse Bypassgefäße werden deutlich seltener verwendet als arterielle Bypassgefäße",
"Es kann pro Patient nur eine A. throacica interna als Bypassgefäß verwendet werden",
"Die A. gastroepiploica eignet sich nicht als Bypassgefäß"]},
{"text": "Welches Symptom spricht am ehesten für einebronchiale Obstruktion?",
"answers":["Brummen",
"Giemen",
"Stridor",
"verlängertes Exspirium",
"feuchte Rasselgeräusche"]},
{"text": "Welche Nachbarschaftsverhältnisse sind beim rechten Lungenhilus zu beachten?",
"answers":["Auf der mediastinalen Seiten verläuft dorso-kranial die V. azygos",
"Auf der mediastinalen Seiten verläuft dorso-kranial der Aortenbogen",
"Das Lig. pulmonale zieht vom Hilus aufwärts zum Apex pulmonis",
"Die Cisterna chyli ist zwischen den Gefäßaästen ausgebreitet",
"Der N. phrenicus kreuzt zwischen den Pleurablättern"]},
{"text": "Welche typischen Komplikationen gehören zu der akuten Typ-B Aortendissektion?",
"answers":["Herzbeuteltamponade, Hemiplegie, Paraplegie",
"Herzbeuteltamponade, Paraplegie, Claudicatio",
"Hemiplegie, Paraplegie, abdominale Ischämie",
"Paraplegie, abdominale Ischämie, Claudicatio",
"Hemiplegie, abdominale Ischämie, Claudicatio"]},
{"text": "Was wird als ein Maß für die körperliche Leistungsfähigkeit durch die PWC170 bei der Untersuchung mit dem Ergometer beschrieben?",
"answers":["die 170 Sekunden lang erbrachte Maximalleistung",
"die auf eine Körpergröße von 170cm standardisierte Leistung bei maximaler Sauerstoffaufnahme",
"die bei einem systolischen Blutdruck von 170 mmHg erbrachte Leistung",
"die pro 170mL aufgenommenem Sauerstoff erbrachte Leistung",
"die bei einer Herzfrequenz von 170 bpm erbrachte Leistung"]},
{"text": "Welches Vorgehen wird zur langfristigen Minderung der Angst bei psychogenen Herzbeschwerden nicht (!) empfohlen?",
"answers":["Ernstnehmen der körperlichen Symptomatik",
"Durchführung einer kardialen Erstdiagnostik",
"Ausführliche Erörterung der Befunde und ihrer Bedeutung",
"Vermeidung psychosozialer Auslösungsfaktoren",
"Einsatz von Anxiolytika"]},
{"text": "Welcher klinische Zustand eines Patienten nach schwerem Thoraxtrauma stellt eine Indikation für einen thoraxchirurgischen Eingriff dar?",
"answers":["Rippenserienfraktur",
"Hämatopneumothorax",
"Lungenkontusion",
"atemabhängige Schmerzen"]},
{"text": "Welches der folgenden Krankheitsbilder/Therapieverfahren führt in der Regel nicht (!) zu einer Anschlussheilbehandlung?",
"answers":["Akuter Myokardinfarkt",
"elektive PTCA mit Stentimplantation",
"koronare Bypass-Operation",
"Dekompensierte Herzinsuffizienz",
"Herzklappen-Operation"]},
{"text": "Wo wird eine Thoraxdrainage in Bülau-Position typischerweise eingelegt?",
"answers":["2. Interkostalraum in der mittleren Axillarlinie",
"5. Interkostalraum in der vorderen Axillarlinie",
"2. Interkostalraum in der Medioklavikularlinie",
"3. Interkostalraum in der hinteren Axillarlinie"]},
{"text": "Was trifft für die Diagnostik bei Patienten mit valvulärer Herzinsuffizienz zu?",
"answers":["Ein kardiales MRT ist zentraler Bestandteil der Diagnostik relevanter Vitien",
"Echokardiographisch lässt sich die Punpfunktion des Herzens gut beurteilen, relevante Vitien sind per Echokardiographie jedoch nicht sicher auszuschließen",
"Luftnot ist auch bei valvulärer Herzinsuffizienz ein Leitsymptom"]},
{"text": "Was mache ich bei Feststellung eines 2cm großen Rundherdes in der Lunge?",
"answers":["PET-CT",
"Mediastinoskopie",
"Operation",
"histologische Sicherung"]},
{"text": "Mit welchen besonderen Nebenwirkungen müssen Sie bei der Therapie mit Amiodaron rechnen?",
"answers":["Störungen der Schilddrüsenfunktion",
"Angioödem",
"Herzklappenfibrose",
"Hörverlust"]},
{"text": "Welche der Aussagen zum Pneumothorax trifft nicht (!) zu?",
"answers":["Ein Pneumothorax kann asymptomatisch verlaufen",
"Ein Spannungspneumothorax wird erst beim Rezidiv operativ versorgt",
"Jeder Pneumothorax kann potentiell zum Spannungspneumothorax führen",
"Im Notfall rechtfertigt die klinische Diagnose eines Spannungspneumothorax die sofortige Anlage einer Thoraxdrainage"]},
{"text": "Welche Aussage zur elektrischen Therapie akuter Herzrhythmusstörungen ist richtig?",
"answers":["Für die elektrische Therapie akuter Herzrhythmusstörungen ist eine Intubationsnarkose erforderlich",
"Ein passagerer Herzschrittmacher zur Therapie akuter bradykarder Herzrhythmusstörungen stimuliert das Herz über eine Sonde, die über die V. jugularis interna in die linke Herzkammer eingebracht wird",
"Alle Patienten mit einem linksventrikulären Schlagvolumen unter 35ml erhalten primärprophylaktische einen internen Defibrillator",
"Bei Patienten mit Herzschrittmacher ist eine Defibrillation kontraindiziert, da sich die Programmierung des Herzschrittmachers durch die Energieabgabe ändern könnte",
"Die Kardioversion akuter Herzrhythmusstörungen erfolgt R-Zacken-getriggert, damit die Energie nicht in der vulnerablen Phase abgegeben wird"]},
{"text": "Bei einem 40-jährigen Mann, der sich seit 10 Tagen schwach und müde fühlts, kommt es nun zu rezidivierenden Fieberschüben mit Schüttelfrost. Es bestehen keine relevanten Vorerkrankungen. Bei der Untersuchung fallen auskultatorisch ein Herzgeräusch sowie eine Tachykardie auf. Die Blutsenkungsgeschwindigekeit und CRP-Konzentration im Serum sind erhöht, ferne liegt eine normozytäre Anämie vor. Welche beiden Untersuchungen sollten als nächstes durchgeführt werden?",
"answers":["Elektrogardiogramm und CT des Thorax",
"Knochenmarkpunktion und Echokardiographie",
"Blutkulturen und Knochenmarkspunktion",
"Echokardiographie und Blutkulturen"]},
{"text": "Bei einer 63-jährigen Patientin wird in der 24-Stunden-Blutdruckmessung eine arterielle Hypertonie diagnostiziert. Der Tagesmittelwert beträgt 150/93mmHg. Der Taillenumfang der Patientin ist 93cm. Der BMI ist 29kg/m^2. Der Vater hatte im Alter von 80 Jahren einen Schlaganfall, die Mutter hat einen Diabetes mellitus Typ II. In der Dopplersonographie der hirnversorgenden Gefäße finden sich Plaques in der A. carotis interna bds. und die Pulswellengeschwindigkeit beträgt 13m/s. Welche kardiovaskulären Risikofaktoren oder Endorganschäden liegen bei der Patientin vor?",
"answers":["Geschlecht, Alter, Diabetes mellitus",
"Hyperlipoproteinämie, Mikroalbuminurie, Linksherzhypertrophie",
"Adipositas Grad 1, koronare Herzkrankheit, positive Familienanamnese",
"Plaques in der A. carotis interna, Elastizitätsverlust der Gefäße, erhöhter Taillenumfang",
"Adipositas, isoliert systolische Hypertonie, Niereninsuffizienz"]},
{"text": "Welche Räume trennt das Septum aorticopulmonale?",
"answers":["rechtes und linkes Atrium",
"rechten und linken Sinus venosus",
"Ausstrombahnen der Ventrikel",
"Arcus aortae und linke A. pulmonalis"]},
{"text": "Kardiomyopathien sind als Erkrankungen definiert, bei denen der Herzmuskel strukturell und funktionell abnormal ist. Welche Erkrankung zählt nicht (!) dazu?",
"answers":["Hypertrophe Kardiomyopathie",
"Dialatative Kardiomyopathie",
"Restriktive Kardiomyopathie",
"Sarkoidose mit Beteiligung des Herzens",
"Arrhythmogene rechtsventrikuläre Kardiomyopathie"]},
{"text": "Frau Kaiser stellt sich erstmalig in ihrer pneumologischen Praxis vor. Sie stellen anhand des klinischen Bildes, der Lungenfunktionsuntersuchung und der Computertomographie des Thorax die Diagnose eines ausgeprägten Lungenemphysems. In der Blutgasanalyse zeigt sich eine schwere Hypoxämie. Welche Aussage zur Genese der Hypoxämie ist richtig?",
"answers":["Durch die obstruktive Ventilationsstörung ist das Atemminutenvolumen stark reduziert, was eine Hypoxämie zur Folge hat.",
"Der Verlust an Gasaustauschfläche durch Destruktion des Lungenparenchyms bedingt eine Diffusionsstörung und somit eine Hypoxämie.",
"Ein Lungenemphysem führt zu einer verminderten Sauerstoffaufnahme in den Lungenkapillaren infolge einer verkürzten erythrozytären Passagezeit"]},
{"text": "Eine 46-jährige sonst gesunde Lehrerin stellt sich in ihrer Praxis vor. Seit drei Monaten besteht ständig ein trockener Reizhusten ohne Fieber und ohne allgemeines Krankheitsgefühl. Sie raucht nicht und hat auch in der Vergangenheit nie geraucht. Es bestehen keine Symptome einer Sinusitis und keine Rhinorrhoe. Ihr sind keine Infekte im letzten Jahr erinnerlich. Aufgrund ihres Berufes mit ständigem Kontakt zu Kindern achtet sie sehr auf den aktuellen Impfstatus: alle empfohlenen Impfungen wurden erst im Vorjahr aufgefrischt. Es besteht außerdem Sodbrennen und gelegentlich saures Aufstoßen. Der auskultatorische Befund der Lunge und der Röntgen-Thorax in zwei Ebenen sind ohne pathologischen Befund. Welches Vorgehen ist zur Abklärung der Hustenursache am sinnvollsten?",
"answers":["CT-Thorax zum Ausschluss eines Bronchialkarzinoms",
"Ergometrie zur Abklärung eines möglichen Belastungsasthmas",
"Pertussis-PCR aus einem Nasopharyngealabstrich unter der Verdachtsdiagnose eines Keuchhustens",
"Sputumkultur auf säurefeste Stäbchen zum Ausschluss einer offenen Tuberkulose",
"Therapieversuch mit Protonenpumpeninhibitoren über 8 Wochen bei Verdacht auf refluxbedingten Husten"]},
{"text": "Welches Medikament ist zur Akuttherapie des Asthma bronchiale am ehesten geeignet?",
"answers":["kurzwirksame Beta-2-Sympathomimetika",
"langwirksame Beta-2-Sympathomimetika",
"inhalative Glukokortikoide",
"Theophyllin",
"Anticholinergika"]},
{"text": "Ein 38-jähriger Mann bemerkt bei körperlicher Anstrengung einen stechenden Schmerz in der linken Brust. Kurz darauf treten leichte Atemnot und Reizhusten auf. Innerhalb von Stunden nimmt die Atemnot erheblich zu. Der eintreffende Arzt findet ihn mit einer kleinen Blutdruckamplitude. Tachykardie von 140/min und einer Einflusstauung im Halsvenenbereich vor. Welche ist differentialdiagnostisch am ehesten die zu stellende Arbeitsdiagnose des Notarztes?",
"answers":["Paroxysmale ventrikuläre Tachykardie",
"Lungenembolie",
"Pleuritis sicca",
"Spannungspneumothorax",
"Herzinfarkt mit Kammerwandruptur"]},
{"text": "Was ist ein histologisches Charakteristikum des Typ B3 Thymoms?",
"answers":["es dominieren Lymphozyten",
"es dominieren Epithelzellen",
"es zeigt eine gleichmäßige Verteilung von Lymphozyten und Epithelzellen",
"es weist keine unreifen (Tdt+) T-Zellen auf"]},
{"text": "Bei einem Patienten mit respiratorischer Störung auf der Intensivstation möchten Sie abklären, ob ein vermindertes systemisches Sauerstoffangebot (DO2) vorliegt. Welcher der folgenden Parameter wird für die Berechnung der DO2 benötigt?",
"answers":["Herzzeitvolumen",
"Atemminutenvolumen",
"Plasmavolumen",
"Atemfrequenz",
"Oxygenierungsindex"]},
{"text": "Im Rahmen der neurohumoralen Aktivierung bei kardialer Funktionsstörung werden Mechanismen aktiviert, die zu einer Kontraktilitäts- und Herzfrequenzsteigerung im gesunden Herzmuskel führen. Welches Wirkprinzip der kontinuierlichen Katecholamin-Ausshüttung potenziert den Teufelskreis der Herzinsuffizienz-Pathogenese",
"answers":["Kontraktilitätssteigerung über Beta-1-Rezeptoren am Myokard",
"Bradykarde Wirkung von Katecholaminen",
"Erhöhung des systemvaskulären Widerstands infolge einer Vasokonstriktion über Alpha-1-Adrenorezeptoren",
"Steigerung der renalen Perfusion"]},
{"text": "Ein 50-jähriger, männlicher Patient präsentiert sich mit akut einsetzenden, heftigen thorakalen Schmerzen, die in den Rücken zwischen die Schulterblätter ausstrahlen. Ineinem sofort angefertigten EKG zeigen sich T-Negativierungen in I, aVL, V5 und V6, jedoch keine ST-Hebungen oder Senkungen. Welche Aussage ist richtig?",
"answers":["Ein akutes Koronarsyndrom ist ausgeschlossen",
"Ein NSTEMI ist wahrscheinlich",
"Es handelt sich um eine Lungenarterienembolie",
"Differentialdiagnostisch sollte an eine Aortendissektion gedacht werden"]},
{"text": "Bei welcher Lungenerkrankung finden sich im Lungenparenchym interstitielle Ansammlungen von Entzündungszellen?",
"answers":["Bei der pulmonalen arteriellen Hypertonie",
"Bei der Lungenfibrose",
"Bei der pulmonalen Hypertonie",
"Bei dem Lungenödem"]},
{"text": "Was ist eine kardiale Ursache einer zentralen Zyanose?",
"answers":["Infarkt-Ventrikelseptumdefekt",
"Vorhofseptumdefekt",
"Persistierender Ductus arteriosus Botalli",
"Fallot- Tetralogie",
"Persistierende linke obere Hohlvene"]},
{"text": "Welche Aussage zu den invasiven Behandlungsoptionen bei Herzinsuffizienz trifft nicht (!) zu?",
"answers":["Ein ICD (Implantierbarer Cardioverter Defibrillator) wird bei Patienten mit diastolischer Herzinsuffizienz zur Senkung des Risikos für einen plötzlichen Herztod empfohlen",
"Die kardiale Resynchronisationstherapie (CRT) erfordert einen verbreiterten QRS-Komplex im EKG und eine reduzierte linksventrikuläre Ejektionsfraktion",
"Eine koronare Bypass-Operation wird bei Patienten mit Angina pectoris und signifikanter Hauptstammstenose empfohlen",
"Ein linksventrikuläres Unterstützungssystem wird bei ausgewählten Patienten mit terminaler Herzinsuffizienz empfohlen"]},
{"text": "Welche diagnostischen Maßnahmen sind entsprechend der Anamnese und der Beschwerden bei Patienten mit Herzinsuffizienz inidiziert?",
"answers":["Ein EKG ist nur bei Verdacht auf eine ischämische Kardiomyopathie sinnvoll",
"Ein kardiales MRT gehört zur Basisdiagnostik",
"Eine Echokardiographie ist nur bei auffälliger Auskultation sinnvoll",
"Ein Lungenfunktionstest ist nicht sinnvoll, weil Herzinsuffizienzpatienten nur selten an begleitenden Lungenerkrankungen leiden",
"Ist eine Echokardiographie nicht möglich, lässt sich bei symptomatischen Patienten auch durch die Bestimmung von Biomarkern wie NTproBNP (N-terminales pro Brain natriuretisches Peptid) schnell eine relevante, unbehandelte Herzinsuffizienz ausschließen"]},
{"text": "Ihnen stellt sich eine 58jährige Patienten vor (Gewicht: 80kg, Größe:158cm). Sie klagt über plötzlich aufgetretene heftige Atemnot, seit sie aus dem Urlaub zurück ist. Angefangen habe das Ganze auf dem Flughafen. Begleitend sei ein unproduktiver Husten aufgetreten. Als Vorerkrankung gibt sie eine chronisch-obstruktive Lungenerkrankung (COPD, GOLD II) und eine Hypercholesterinämie an. Herzfrequenz 130/min, Atemfrequenz 30/min. Mindestens 30 Pack-Years. Wie lautet die wahrscheinlichste Diagnose?",
"answers":["Lungenembolie",
"Akutes Koronarsyndrom",
"Status asthmaticus",
"Bronchiektasienkrise",
"Spontanpneumothorax"]},
{"text": "Eine erwachsene Patientin mit asthma bronchiale erzählt, dass sie circa zwei Mal wöchentlich Dyspnoe habe. Seit kurzem ist bei der Patientin eine deutliche Verschlechterung des Asthmas zu verzeichnen. Sie hat jetzt fast täglich und häufig nachts Symptome. Auskultatorisch stellen Sie Giemen, Brummen und Pfeifen über beiden Lungen fest. Welche der folgenden inhalativen Medikationen könnte, basierend auf der Ihnen bekannten Stufentherapie, zusammen mit einem inhalativen Glukokortikosteroid, am ehesten zur Prophylaxe nächtlicher Asthmaanfälle im Rahmen der hier geschilderten nächtlichen Symptomatik zum Einsatz kommen?",
"answers":["Salmeterol",
"Salbutamol",
"Terbutalin",
"Reproterol",
"Ipratropium"]},
{"text": "Das Angioödem gilt als seltene und schwerwiegende Nebenwirkung der ACE-Hemmer. Welche Maßnahme zur Reduktion des Risikos dieser Nebenwirkung ist sinnvoll? (ACE: Angiotensin Converting Enzyme)",
"answers":["Bestimmung der Kreatin-Kinase (CK)",
"Bestimmung des Bradykinins",
"Bestimmung der Plasma-Renin-Aktivität",
"Kombination mit einem AT1-Antagonisten",
"Aufklärung des Patienten über die Frühsymptome des Angioödems"]},
{"text": "Welches Therapieprinzip liegt der koronararteriellen Bypass-Operation zugrunde?",
"answers":["Es handelt sich um eine ursächliche Heilbehandlung der koronaren Herzerkrankung",
"Die Stenose/n der Koronararterie wird/werden beseitigt",
"Der Blutfluss im Bypass umgeht den stenosierten Abschnitt der Koronararterie",
"Die Ausbildung von Kollateralgefäßen zwischen nicht-stenosierten zu stenosierten Koronararterien wird stimuliert",
"Die Neubildung von Myokardgewebe in Infarktarealen wird angeregt"]},
{"text": "Ein 33-jähriger Mann wird wegen einer Raumforderung des Thymus operiert. Das histologische Präparat zeigt Veränderungen, die durchaus zu einem Typ A Thymom passen. Allerdings kann ein lymphoblastisches Lymphom nicht sicher ausgeschlossen werden. Welche Immunhistologie ist hierbei hilfreich?",
"answers":["CD3",
"CD43",
"CD99",
"Pan-Zytokeratin",
"terminal deoxynucleotidyl transferase (TdT)"]},
{"text": "Welches klinische Symptom könnte einen erhöhten Verdacht für eine mediastinale Ifiltration eines Tumors darstellen?",
"answers":["Husten",
"Schnupfen",
"Heiserkeit",
"Auswurf"]},
{"text": "Welcher Art von Thoraxtrauma ist eine Schussverletzung typischerweise zuzuordnen?",
"answers":["stumpfes Trauma",
"Dezelerationstrauma",
"penetrierendes Trauma",
"Barotrauma"]},
{"text": "Welche Aussage zur Kardioversion von Vorhofflimmern und -flattern ist richtig?",
"answers":["Thromben im linken Vorhofohr müssen per transösophagealer Echokardiographie nur vor elektrischer, aber nicht vor medikamentöser Kardioversion ausgeschlossen werden",
"Betablocker sind effektive Substanzen zur medikamentösen Kardioversion",
"Amiodaron ist auch zur Kardioversion bei Patienten mit einer Herzinsuffizienz geeignet",
"Digitalisglykoside sollten insbesondere bei Patienten mit Bradyarrhythmia absoluta eingesetzt werden",
"Bei Vorhofflattern entstehen im Gegensatz zum Vorhofflimmern keine Vorhofthromben, so dass hier eine Antikoagulation entfallen kann"]},
{"text": "Die Umstellung des Kreislaufs bei der Geburt ist begleitet von Änderungen in der Perfusion der Herzkammern. Warum kommt es im Bereich der Vorhöfe zum Verschluss des Vorhofseptums?",
"answers":["Der Druck im rechten Atrium steigt an",
"Der Blutfluss über die Lungenvenen nimmt zu",
"Das kraniokaudale Wachstum bringt das Septum primum in Kontakt mit der Ventilebene des Herzens",
"Der Sinus coronarius öffnet sich in das rechte Atrium",
"Der rechte Sinus venosus wächst in den rechten Vorhof ein"]},
{"text": "Für die Akuttherapie der dekompensierten Herzinsuffizienz können unter hämodynamischem Monitoring im Einzelfall kurz wirksamme Stickstoffmonoxid-Donoren wie Nitroprussidnatrium (NPN) in Betracht kommen. Welche Aussage zu einer möglichen Optimierung der Hämodynamik duch NPN trifft zu?",
"answers":["Durch NPN wird die Synthese cyclischen GMPs (Guanosinmonophospat) in Gefäßmuskelzellen reduziert.",
"Infolge erniedrigter intrazellulärer Kalziumspiegel kommt es zur Senkung des systemvaskulären Widerstands.",
"Eine Aktivierung der SERCA (Sarcoplasmic/Emicn culum Calcium ATPase) durch vermiderte Phospholamban-Phosphorylierung steigert die Kontraktilität.",
"NPN aktiviert direkt die Adenylatcyclase im Herzmuskel"]},
{"text": "Welches Sympthom spricht am ehesten für eine bronchiale Obstruktion?",
"answers":["Brummen",
"Giemen",
"Stridor",
"verlängertes Expirium",
"feuchte Rasselgeräusche"]},
{"text": "In der Rettungsstelle stellt sich ein 22-jähriger mann mti einer rektal gemessenen Temperatur von 38 Grad und atemabhängigen retrosternalen Brustschmerzen, die siet ca. 3 Tagen betehen vor. Der Pateint hat keine Vorerkrankungen, die Familienanamnese ist unauffällig. Medikamente oder Drogen werden verneint. Im EKG fallen deutlich ST-Streckenhebungen in II, III aVF sowie V1-V6 auf. Welche Diagnose ist anhad der vorliegenen Informationen am wahrscheinlichsten?",
"answers":["Hinterwandinfarkt bei Verschluss der rechten Koronararterie",
"Virale Perimyokarditis",
"Bakterielle Endokarditis",
"Postinfarktpneumonie nach stattgehabter Lungenarterienembolie"]},
{"text": "Nach Schussverletzung der linken Thoraxhälfte wird eine Thoraxdrainage angelegt. Welche Maßnahme ist bei der Entleerung von mehr als 1500ml Blut nach Drainageanlage und instabilem Kreislauf am ehesten inidiziert?",
"answers":["In dieser Situation wird abwartend behandelt, da die Prognose stets infaus ist",
"Prioritär soll jetzt eine Anxiolyse erfolgen",
"In dieser Situation wird die Throaxdrainae sofort abgeklemmt",
"Es kann eine sofortige Thorakotomie indiziert sein"]},
{"text": "In Ihrer Praxis stellt sich ein 40-jähriger Patient mit einer schwer einstellbaren arteriellen Hypertonie sowie rezidivierenden hypertensiven Entgleisungen verbunden mit Blässe, Herzrasen und Schweißausbrücken vor. Der Patient hat eine diagnostizierte Neurofirbomatose Typ I. Welche Verdachtsdiagnose stellen Sie und welche diagnostische Maßnahme leiten Sie zunächst ein?",
"answers":["Primärer Hyperaldosteronismus - Bestimmung des Aldosteron-Renin-Quotient im Blut",
"Phäochromozytom - Messung von Metanephrinen und Katecholaminen im Urin und Plasma",
"Cushing Syndrom 24 Stunden Urinausscheidung von Kortisol",
"Nierenarterienstenose - Duplexsonographie der Nierenarterien"]},
{"text": "Welche Aussage ist bezogen auf Patienten mit einer chronisch-obstruktiven Lungenerkrankung COPD und begleitender Panikstörung im Vergleich zu Patienten mit COPD ohne Panikstörung richtig?",
"answers":["Die COPD Patienten mit Panikstörung haben nur selten katastrophierende Gedanken in bezug auf die Atemnot",
"Bei den COPD Patienten mit Panikstörung ist keine höhere Angstsensitivität nachweisbar",
"Die COPD Patienten mit Panikstörung weisen in der Regel anamnestisch eine höhere Anzahl kürzlich aufgetretener belastender Lebensereignisse auf.",
"COPD Patienten mit Panikstörung weisen ähnlich schwere Depressionsgrade auf wie COPD Pateinten ohne Panikstörung"]},
{"text": "Was kommt als Ursache für ein Hämatoperiakrd am ehesten in Betracht?",
"answers":["akute virale Myokarditis",
"verkalkte tuberkulöse Perikarditis",
"Aortendissektion Typ A nach Stanford",
"Aortenklappeninsuffizienz bei Endokarditis",
"Hypertrophe Kardiomyopathie"]},
{"text": "Welche Aussage zur arteriellen Blutgasanalyse trifft zu?",
"answers":["Der pCO2 gibt den Hämoglobin-gebundenen Anteil an CO2 an",
"Der Sauerstoffpartialdruck kann an der Oxyhämoglobinfraktion abgelesen werden",
"Der physikalisch im Blut gelöste Sauerstoff kann an der Sauerstoffsättigung abgelesen werden",
"Die angegebene Sauerstoffsättigung ist auf den pH normalisiert",
"Der arteriell Sauerstoffgehalt kann aus der arteriellen Blutgasanalyse errechnet werden"]},
{"text": "Bei einem gesunden jungen Mann (26 Jahre alt, 78kg, 16% Körperfettmasse}, der regelmäßig drei mal pro Woche für eine Stunde Freizeitsport treibt, jedoch kein Leistungssportler ist, wird ein PWC 170 Leistungstest durchgeführt. Wie hoch ist die dabei zu erwartende Leistungsfähigkeit?",
"answers":["circa 20% der VO2 max",
"maximal 170 Joule/s",
"rund 3,5ml O2/kg Körpergewicht /min",
"circa 3 Watt/Kg Körpergewicht",
"mindestens 700 Watt absolut"]},
{"text": "Ein 70-jähriger Patient stellt sich aufgrund einer zunehmenden ödematoösen Schwellung beider Augenlider vor. Welche Lokalisation einer Raumforderung könnte diese Symptomatik am besten erklären?",
"answers":["Hirnstamm",
"Hypophyse",
"Sinus maxillaris",
"Tuba auditiva",
"Mediastinum"]},
{"text": "Welche Aussage zur Anamnese und körperlichen Untersuchung von Patienten mit Verdacht auf Herzinsuffizienz trifft zu?",
"answers":["Palpitationen und Schwidel sind untypisch",
"Luftnot zählt nicht zu den Leitsymptomen",
"Angina pectoris-Symptomatik weist auf eine koronare Herzkrankheit als zugrunde liegende Ursach hin, kann aber auch durch eine Aortenklappenstenose verursacht werden.",
"Periphere Ödeme sind typisch für eine linksführende kardiale Demkompression",
"Ein Lungenödem ist das Kardinalsymptom der rechtsführenden kardialen Dekompensation"]},
{"text": "Auf der Intensivstation entwickelt eine 75-jährige Patientin, die kurz zuvor wegen eines akuten Myokardinfarktes aufgenommen wurde, progrediente Dyspnoe. Sie kann nur noch aufrecht sitzen und hustet schaumiges Sekret ab. Bei Auskultation der Lunge fallen Ihnen feinblasige Rasselgeräusche über der gesamte Lunge auf. Welche Verdachtsdaignose stellen Sie?",
"answers":["Pneumonie",
"Asthmaanfall",
"Lungenarterienembolie",
"Pneumothrax",
"Lungenödem"]},
{"text": "Welche Aussage zur interventionellen Therapie des akuten Koronarsydroms ist richtig?",
"answers":["Das Vorhandensein oder Fehlen von ST-Hebungen im EKG hat einen bedeutenden Einflsus auf den Zeitpunkt der Koronarangiographie",
"Bei einem Nicht-ST-Hebungs-Infarkt wird eine invasive Strategie innherhalt von 72 Stunden empfohlen",
"Bei einem ST-Hebungsinfarkt wird eine invasive Strategie innerhalb von 24 Stunden empfohlen",
"Bei einem ST-Hebungsinfarkt soll vor der Herzkatheterdiagnostik eine Lysetherapie erfolgen"]},
{"text": "Bei einer 40-jährigen Patientin mit Anti-Scl70-Antikörper-positiver systemischer Sklerose hören Sie beidseits basal ein endexspiratorisches Knisterrasseln. Welche sturkurellen Veränderugnen ind er Lunge liegen diesem Befund am wahrscheinlichsten zugrunde?",
"answers":["Bakterielle Entzündung in den Unterlappen",
"Abszess beidseits basal",
"Oliterative Vaskulopathie im präkapillären Bett",
"Interstitielle Veränderungen mit entzündlichen Infiltraten"]},
{"text": "Welcher Befund erklärt am ehesten die bei mäßiger Belastung einsetzender Dyspnoe eines Patienten?",
"answers":["Linksverntrikuläre Ejektionsfraktion von 50% bei anterolateraler Hypokinesie (eine koronare Herzerkrankung wurde invasiv vor 3 Monaten ausgeschlossen)",
"Aortenklappenstenose Grad I (mittlere Druchgradient 9mmHG, Öffnungsfläche 1,8cm2)",
"Geringgradige Trikuspidalklappeninsuffizienz",
"Biatriale Dilatation",
"Diastolische Dysfunktion Grad III mit Zeichen eines erhöhren linksvertrikulären enddiastolischen Durckes"]},
{"text": "Sie werden zu einem Patienten in die Notaufnahme mit einem ätiologisch unklaren mediastinalen Tumor gerufen. Mit welcher apparativen Diagnostik erfolgt eine sinnvolle weiter Abklärung?",
"answers":["sofortige Biopsie",
"MRT",
"Beobachtung für 3 Monate",
"Primäre Aufnahme in die endokrinolgische Abteilung"]},
{"text": "Welches ist die aktuell in der Bundesrepublik Deutschland empfohlene Standardtherapie der unkomplizierten Lungentuberkulose?",
"answers":["Isoniazid, Rifampicin, Ethambutol, Pyrazinamid für 2 Monate, gefolgt von Isoniazid, Rifampizin für 4 Monate",
"Isoniazid, Rifampicin, Ethambutol, Pyrazinamid für 6 Monate",
"Isoniazid, Rifampicin für 9 Monate",
"Rifampicin, Clindamycin, Fidaxomicin, Clarithromycin für 2 Monate, gefolgt von Rifampicin, Clindamycin für 4 Moante"]},
{"text": "Welches der genannten Antihypertensiva hat eine Indikation für die Behandlung eines Patietnen mit arterieller Hypertonie und chronischer Herzinsuffizienz im Stadium NYHA II ohne Ödeme",
"answers":["Doxazosin",
"Ramipril",
"Furosemid",
"Amlodipin"]},
{"text": "Welche der folgenden Therapieformen ist eine adjuvante Therapie?",
"answers":["Eine präoperative Chemotherapie",
"Postoperative Bestrahlung der Axilla bei einer Patientin mit Mammakarzinom",
"Schädelbestrahlung bei einer Patientin mit kleinzelligem Bronchialkarzinom",
"Bestrahlung von innen mittels direkt ins Organ eingebrachter Kurzdistanzstrahlenquellen bei einem Patienten mit Prostatakarzinom"]},
{"text": "Welche Aussage zu Komplikationen und Folgeerkrankungen bei Vorhofflimmern ist korrekt?",
"answers":["Ohne ausreichende Antikoagulation führt Vorhofflimmern häufig durch Thrombenbildung im rechten Vorhof zu Lungenarterienembolien",
"Eine Bradyarrhythmyia absoluta bei Vorhofflimmern fürht nie zu Kammerfrequenzen unter 50/min und ist deshalb nicht mit Synkopen assoziiert",
"Vorhofflimern ist für etwa 20% der Schlaganfälle in Europa verantwortlich",
"Bei paroxysmalem Vorhofflimmern besteht unabhängig von weiteren Risikofaktoren immer die Indikation für eine orale Antikoagulation",
"Eine elektrische Kardioversion kann auch bei länger bstehendem Vorhofflimmer (>48h) ohne echokardiographischen Ausschluss von Thromben im linken Vorhofohr sicher durchgeführt werden, wenn der Patient vor der kardioversion Heparin erhält."]},
{"text": "Mittels CT des Thorax wird bei einem Patienten wegen eines peripheren Rundherdes in der Lunge und bilaterale hiläre und mediastinale Lymphknotenvergrößerungen der Verdacht auf ein Bronchialkarzinom gestellt. Welches ist der nächste diagnostische Schritt?",
"answers":["Positronen-Emissionstromographie kombiniert mit Magnetresonanztomographie",
"Immunzytologie des Sputums",
"Bronchoskopie mit endobronchialem Ultraschall",
"Ganzkörperskelettszintigraphie",
"Pulmonalis-Angiographie"]},
{"text": "Ein 45-jähriger Patient leidet seit Jahren unter den Folgen einer dilatativen Kardiomyopathie. Inzwischen tritt Dyspnoe bereits in Ruhe auf. Es zeigen sich Unterschenkelödeme. Echokardiographisch liegt eine stark eingeschränkte linksvertrikuläre Auswurffraktion von 15% vor. Eine umfangreiche medikamentöse Herzinsuffizienztherapie ist bereits etabliert worden. Welche Aussage zu möglichen weitern Therapieoptionen trifft zu?",
"answers":["Eine Herztransplantation ist die einzige kurative Therapie",
"DIe Implantation eines Kunstherzens ist keine Option, da dann eine Herztransplantation kontraindiziert ist",
"Das Kunstherz ist die einzige verfügbare Möglichkeit der mechanischen Kreslaufunterstützung",
"Patienten mit Kunstherz können as Krankenhaus nicht verlassen",
"Ein Kunstherz kann nur für die Unterstützung des linken Ventrikels verwendet werden."]},
{"text": "Welche Zuordnung von Krankheitsbild und Befund in der körperlichen Untersuchung ist richtig?",
"answers":["Fremdkörperaspiration - expiratorischer Stridor",
"Fremdkörperaspiration - Brummen, Pfeifen und Giemen",
"Anaphylaxie - inspiratorischer Stridor",
"Anaphylaxie - Brummen, Pfeifen und Giemen"]},
{"text": "Welche Maßnahme ist in der Regel Teil einer physiotherapeutisch durchgeführten Atemtherapie?",
"answers":["Trainingstherapie",
"Lymphdrainage",
"Fußreflexzonentherapie",
"Kompressionsbandagierung",
"Atemlenkung"]},
{"text": "Welche Aussage zu den Behandlungszielen im Rahmen der Rehabilitation einer koronaren Herzkrankheit trifft NICHT zu?",
"answers":["Steigerung der krankheitsbezogenen Lebensqualität",
"Vermediung von Angina-pectoris-Beschwerden",
"Verminderung der körperlichen Belastungsfähigkeit",
"Reduktion der kardiovasculären Morbidität",
"Verminderung von KHK-assoziierten psychischen Erkrankungen"]},
{"text": "Eine 64 jährige dünne Pateintin (BMI 19,3) stellt sich in der Notaufnahme mit rechtsseitigen Oberbauchschmerzen, Übelkeit und Unwohlsein vor. DIe Symptome sind am Vorabend aufgetreten und seitdem kontinuierlich vorhanden, sie hat Dyspnoe und Palpitationen. Seit vielen Jahren hat sie einen arteriellen Hypertonus und einen Diabetes mellitus Typ 2. Die Patientin ist Raucherin. In der körperlichen Untersuchung seehn Sie eine schweißige Patientin mit blassem Hautkolorit. Was ist die wahrscheinlichste Diagnose?",
"answers":["Nierenkolik",
"Gallenkolik",
"Akuter Myokardinfarkt",
"Aortendissektion"]},
{"text": "Bei einem 65-jährigen Patienten mit einer chronisch-obstruktiven Lungenerkrankung COPD besteht nach Anlage eines zentralen Venenkatheters in der recht V. subclavia eine zunehmende Dyspnoe. Was ist die wahrscheinlichste Ursache?",
"answers":["ein primörer Spontanpneumothorax",
"ein sekundärer Spontanpneumothorax",
"ein traumatischer Pneumothorax",
"ein iatrogener Pneumothorax"]},
{"text": "Was spricht makroskopisch am eheste für Malignität?",
"answers":["Kapselbildung",
"erhaltenes Fettgewebe",
"unscharfte, knotenartige äußere Begrenzung",
"Größe"]},
{"text": "Bei einem 56-jährigen Patienten mit einer antihypertensiven Dreifachkombination besteht aus Hydrochlorothiazid, Ramipirl und Verapamil mit adäquater Dosierung und gesicherter Medikamenteneinnahme geehn Sie von einer therapieresistenten Hypertonie aus. Weitere Erkrankungen sind nicht bekannt. Um welchen der folgenden Wirkstoffe sollte die Kombinationstherapie in dieser Situation ergänt werden?",
"answers":["Spironolacton",
"Midazolam",
"Simvastatin",
"Notroprussid-Natrium"]},
{"text": "Welche Aussage zum malignen Pleuramesotheliom ist richtig?",
"answers":["Es kommt am häufigsten bei jungen, leptosomen Patienten vor",
"Es ist eine anzeigepflichtige Berufskrankheit",
"Wird auch ohne histologische Sicherung behandelt",
"Entsteht durch den Umgang mit Glyphosat"]},
{"text": "Wo wird eine Thoraxdrainage in Monaldi-Postion typischerweise eingelet?",
"answers":["2. ICR mittlere Axillarlinie",
"5. ICR vordere Axillarlinie",
"2. ICR Medioklavikularlinie",
"3. ICR hintere Axillarlinie"]},
{"text": "Welche Aussage zur Herzinsuffizienz trifft zu?",
"answers":["Patienten mit akuter Herzinsuffizienz sind defnitionsgemäß immer hypton (systolischer Blutdruck <90mmHG)",
"Patienten im Lungenödem sind meist hypoton und müssen daher zunächst per intravenöser Volumengabe stabilisert werden.",
"Zu den Basismaßnahmen bei Herzinsuffizienz mit akuter Stauung gehört die Gabe von Schleifendiuretika",
"Zu den Basismaßnahmen bei Herzinsuffizienz mit akuter Stauung gehör immer die Gabe von Adrenalin",
"Zu den Allgemeinmaßnahmen bei Herzinsuffizienz mit akuter Stauung gehört eine flache Lagerung des Patienten mit angehobnen Beinen (Schochlagerung)"]},
{"text": "Welcher Score dient zur Abschätzung des Schlaganfallrisikos bei Vorhofflimmern?",
"answers":["NYHA",
"EHRA",
"CHA2DS2-VASc",
"CCS",
"HAS-BLED"]},
{"text": "Ein 30-jähriger Patient mit schwer einstellbarer arterieller Hypertonie stellt sich in einer Praxis vor. Welcher der folgenden Befunde lässt den Arzt am eheten an eine sekundäre Hypertonie denken?",
"answers":["deutlich erhöhte Wanddicke der A. carotis mit einer Initma-Media-Dicke von 1,3mm",
"zentrale Adipositas, Mondgesicht, Striae und Hirsutismus",
"ausgepräge Beinödeme und Orthopnoe",
"Kälteintoleranz und Haarausfall"]},
{"text": "Ein 67-jähriger Patient kommt mit Abgeschlagenheit, einem Gewichtsverlust von 15kg in den letzten zwei Moanten, produktivem Husten, zunehmender Belastungsdyspnoe und intermittieredem Fieber bis 39Grad in die Notaufnahme. Zudem beklagt er Parästhesien am linken Unterarm und eine Kraftminderung der linken Hand, die seit zwei Wochen bestehen. Er raucht seit 47 Jahren rund 1,5 Packungen Zigaretten pro Tag. In der körperlichen Untersuchung fällt ein Horner-Syndrom links auf. Im Rahmen der radiologischen Diagnostik wird eine 4 mal 4 cm große Raumforderung in der Lunge beschrieben. Welche Lage des Tumors erklärt hier am besten die Symptomatik des Patienten?",
"answers":["In direkter Nähe zum Aortenbogen",
"in direkter Nähe zum linken Ventrikel des Herzens",
"In der Lungenspitze links",
"In direkter Nähe zur Bifurkation der Trachea links"]},
{"text": "Welcher Wirkstoff ist ein Kalzium-Antagonist vom Dihydroyridin-Typ?",
"answers":["Verapamil",
"Ramipril",
"Clonidin",
"Amlodipin"]},
{"text": "Direkt nach dem Verzehr selbstgemachter Weihnachtskekse eines Klassenkameraden, fängt ein 8-jähriger Junge in der Schulause plötzlich an zu husten. Außerdem bekommt er keine Luft mehr, die Atmung ist schnell und flach, er entwickelt eine pfeifende Atmung, ist ängstlich und seine Lippe schwillt an. Welchen diagnostischen Schritt - aufgrund welchen Verdachts - veranlasst der ARzt nach der Akutbehandlung wenn er erfährt, dass der Junge eine atopische Dermatitis hat?",
"answers":["Bronchoskopie - Aspiration von Keksteilen",
"Lungenfunktionsprüfung - Asthma bronchiale",
"Allergietest auf Nüsse und Erdnüsse - allergische Reaktion auf Nüsse und Erdnüsse",
"Röntgen-Thorax - Pneumothorax"]},
{"text": "Ein Arzt sieht einen 50 jährigen Mann mit einer Weit fortgeschrittenen Lungenerkrankung in seiner Praxis. Was würde GEGEN eine Listung zur Lungentransplantation bei diesem Patienten sprechen?",
"answers":["eine hochgradige Hypoxie",
"eine chronische ventilatiorische Insuffizienz",
"eine Rechtsherzbelastung bei pulmonaler Hypertonie",
"eine pulmonale Kachexie mit einem BMI von 14"]},
{"text": "Welches ist das adäquateste Verfahren zur bildgesteuerten Biopsie einer pulmonalen Raumforderung?",
"answers":["CT ohne Kontrastmittel",
"CT mit Kontrastmittel",
"konventionelles Röntgen",
"MRT"]},
{"text": "Ein invasiv beatmeter Patient auf einer Intensivstation hat bei reiner Sauerstoffatmung eine peripher gemessene Sauerstoffsättigung von 79%. Welche Aussage trifft NICHT zu?",
"answers":["es handelt sich um eine arterielle Hypoxämie",
"der numerische Wert des arteriellen Sauerstoffpartialdrucks ist größer als der numerische Wert der peripher gemessenen Sauerstoffsättigung",
"Es kann sich um ein akute Lungenversagen nach der Berlin -Definition handeln",
"Akut aufgetreten handelt es sich in o.g. Beispiel um eine Notfallsituation die den Patienten vital bedroht"]},
{"text": "Ein Jugendlicher hat seit vier Monaten trockenen Reizhusten. Da er währned eines Fußballspieles kurzatmig wurde, stellt er sich nun beim Arzt vor. Der klinisch erhobene Befund enthält Gimen und Brummen über beiden Lungen, ein verlängertes Exspirium und hypersonoren Klopfschall. Welche weiteren Angaben würden am ehesten die Diagnose eines Asthma bronchiale stützen?",
"answers":["Blutbild 8000 Leukos, 2,5% Eosinophile",
"funktionelle Residualkapazität: vermindert",
"kapilläre Sauerstoffsättigung: 98%",
"exspiratorischer Peak flow: erhöht",
"forcierte Einsekundenkapazität: vermindert"]},
{"text": "Bei einer 15-jährigen Patientin soll ein Thymom ausgeschlossen werden. Welches Verfahren ist geeignet und geht mit der niedrigsten Exposition inoisierender Strahlung einher?",
"answers":["CT",
"MRT",
"PET-CT",
"Röntgen-Thorax"]},
{"text": "Welche Strategie sollte bei chronischem AV-Block 2. udn 3. Grades zur langfristigen Therapie herangezogen werden?",
"answers":["der Einsatz langwirksamer Anticholinergika",
"die Implantation eines Schrittmachers",
"der Einsatz von Adrenalin-Depotpräparaten",
"es besteht keine Notwenidgkeit zur langfirstigen Therapie, da untergeordnete Schrittmacherzentren die Schlagfrequenz sicherstellen"]},
{"text": "Was ist eine typische frühe Nebenwirkung einer Strahlentherapie?",
"answers":["Leukopenie",
"Entzündung von Schleimhäuten",
"Fibrosierung von Organen",
"Osteoporose",
"Haarausfall"]},
{"text": "Zu welchen typischen Problemen bezogen auf Atmung und Kreislauf kann es bei einer gestörten postnatalen Adaptation kommen?",
"answers":["es kann sich eine Hypoxämie, Hypokapnie und gemischte Alkalose entwickeln",
"Eine gestörte postnatala Adaptation kann den pulmonalen Gefäßwiderstand erhöhen, worduch es zu einem klinisch relevanten Rechts-links-Shunt kommen kann",
"Das Foramen ovale wird innerhalb von Minuten geschlossen",
"Der APGAR Score als Kriterium zur Berurteilung der kardiopulmonalen Adaptation im Neugeborenenalter kann zu einer erhöhten Sauerstoffsättigung führen"]},
{"text": "Was charakterisiert den Phsiological Strain Index?",
"answers":["Er ist eine Kombination aus Herzfrequenz, Umgebungstemperatur und Sauerstoffaufnahme",
"Er erfasst den Hitzestress des Körpers",
"Er beschreibt die mechanische Leistung relativ zum Körpergewicht bei Ausbelastung",
"Er ermöglicht eine nicht-invasive Abschätzung der maximalen Sauerstoffaufnahme"]},
{"text": "Im Rahmen eines hypertensiven Notfalls soll einem Patient GLyceroltrinitrat als Zerbeißkapsel verabreicht werden. Welche Frage sollte dem Patienten vor Gabe dieses Medikamentes gestellt werden, um eine Kontraindikation auszuschließen?",
"answers":["Haben Sie ein Mittel gegen Erektionsstörungen eingenommen?",
"Haben SIe Asthma?",
"Haben Sie einen Diabetes mellitus?",
"Wie alt sind Sie?"]},
{"text": "Was ist ein histologisches Chrakteristikum des Typ A Thymoms?",
"answers":["Es dominieren die Lymphozyten",
"Das Verhältnis von Lymphozyten zu Epithelien ist ausgewogen",
"Es dominieren die Epithelien",
"Es lassen sich zahlreiche TdT+ Thymozyten nachweisen"]},
{"text": "Welche Aussage zu Mitralklappenvitien ist korrekt?",
"answers":["Mitralklappensteonse sind häufiger als -Insuffizienzen",
"Häufigste Ursache einer sekundären Mitralklappeninsuffizienz ist ein Papillarmuskelabriss nach Herzinfarkt",
"Neben der degenerativen Mitralklappeninsuffizienz spielt die funktionielle Mitralklappeninsuffizienz eine wichtige Rolle",
"Im Gegensatz zu Mitralklappenstenose führt auch eine hochgradie Mitralklappeninsuffizienz nicht zu einer linksartrialen Dilatation",
"In der klinischen Untersuchung muss ein Diastolikum an eine Mitralklappeninsuffizienz denken lassen"]},
{"text": "Welchen räumlichen Bezug hat der Recessus costomediastinalis der rechten Pleurahöhle mit dem der linken Pleurahöhle hinter dem Sternum?",
"answers":["Beide Recessus sind über die gesamte Länge des Sternums durch das Mediastinum breit voneinander getrennt",
"Beide Recessus haben über die gesamte Länge des Sternums engen Kontakt zueinander",
"Beide Recessus haben hinter dem Manubrium sterni engen Kontakt zueinander",
"Beide Recessus haben zwischen dem sternalen Ansatz der 2. und 4. Rippe Kontakt zueinander"]},
{"text": "Welches Antihypertensivum ist zum Beginn der Therapie bei einem Patienten nach einem Myokardinfarkt und mit einer arteriellen Hypertonie, nach Ausschluss klarer Kontraindiaktionen, am ehesten geeignet?",
"answers":["Hydrochlorothiazid",
"Nifedipin",
"Metoprolol",
"Doxazosin",
"Furosemid"]},
{"text": "Was versteht man unter einer pulmonalen Hypertonie und was ist deren häufigste Ursache?",
"answers":["erhöhter Druck im Lungenkreislauf (>25mmHg) durch Rechtsherzversagen",
"erhöhter Druck im Lungenkreislauf (>25mmHg) durch Linksherzinsuffizienz",
"erhöhter Druck im Lungenkreislauf (>25mmHg) durch Erhöhung des präkapillaren Widerstandes",
"erhöhter Druck im Lungenkreislauf (>25mmHg) durch rezidivierende Lungenembolie"]},
{"text": "Welche Aussage zur antibiotischen Prophylaxe bei einem Patienten mit einer infektiösen Endokarditis ist richtig?",
"answers":["Jeder Patient erhält bei jedem invasiven Eingriff eine Antibiotikaprophylaxe",
"Jeder Patient mit einer Herzklappenstenose oder -insuffizienz erhält bei jedem invasiven Eingriff eine Antibiotikaprophylaxe",
"Jeder Patient mit einer Herzklappenstenose oder -insuffizienz erhält bei allen zahnäztlichen Eingriffen eine Antibiotikaprophylaxe",
"Die Gabe von Antibiotika zur Prophylaxe einer Endokarditis betifft nur Höchstrisikopatienten bei zahnärztlichen Höchstrisikoeingriffen",
"Eine Antibiotikagabe zur Prophylaxe einer infektiösen Endokarditis wird generell nicht mehr empfohlen"]},
{"text": "Welcher Befund ist am häufigsten mit einem Pleuramesotheliom assoziiert?",
"answers":["Hämatothorax",
"Pnemothorax",
"Pleuraerguss",
"Lungenabszess"]},
{"text": "Eine Patientin mit systemischer Sklerose, rezidivierenden Fingergeschwürden und Teleangiektasien im Gesicht klagt über zunehmende Luftnot bei Belastung. Welche Strukurellen Veränderungen der Lunge, bei welcher Erkrankung sind dafür die wahrscheinlichste Ursache?",
"answers":["obliterative Vaskulopathie bei pulmonaler arterieller Hypertonie",
"obliterative Vaskulopathie bei chronischer Linksherzinsuffizienz",
"interstitielle Lungenerkrankung bei chronischer Linksherzinsuffizienz",
"Überblähung der Lungen mit Rarefizierung der ALveolen bei chronischem Asthma"]},
{"text": "Welche Maßnahme ist dazu geeignet bei einem beatmeten Patienten mit einer respiratorischen Störung das systemische Sauerstoffangebot zu erhöhen?",
"answers":["die Hämoglobinkonzentration anheben und die inspiratorische Sauerstoffkonzentration erhöhen",
"den Beatmungstubus verkürzen (Toraumverkleinerung)",
"den inspiratorischen Plateaudruck um ca. 50% steigern",
"den pH-Wert des Blutes durch Infusion von Natriumbicarbonat alkalisieren",
"den peripheren Gefäßwiderstand durch Infusion von Noradrenalin steigern"]},
{"text": "Welche Befundkonstellation ist für akutes Asthma bronchiale tpyisch?",
"answers":["Atemwegshyperreagibilität - reversible Obstruktion der Atemwege - vermehrte Mukus-Sekretion in den Atemwegen -Emphysem",
"Atemwegshyperreagibilität - reversible Obstruktion der Atemwege - vermehrte Mukus-Sekretion in den Atemwegen - Ödem der Bronchialschleimhaut",
"Atemwegshyporeagibilität - reversible Obstruktion der Atemwege - vermehrte Mukus-Sekretion in den Atemwegen - Ödem der Bronchialschleimhaut",
"Atemwegshyperreagibilität - irreversible Obstruktion der Atemwege - verminderte Mukus-Sekretion in den Atemwegen -Emphysem"]}]

const letters = ['a) ', 'b) ', 'c) ', 'd) ', 'e) ', 'f) ', 'g) ']
const tags = [{label: 'Altfrage', color: 'hsl(49, 100%, 20%)'}, {label: 'Klinisch', color: 'hsl(49, 100%, 30%)'}, {label: 'Theoretisch', color: 'hsl(49, 100%, 50%)'}, {label: 'Querschnittsfach', color: 'hsl(49, 100%, 70%)'}]
function convertQuestion(q) {
    const correctAnswer = _.random(q.answers.length-1)
    const selectedAnswer = _.random(q.answers.length-1)
    return {
        text: q.text,
        id: _.uniqueId(),
        durchschnittRichtig: Math.random(),
        antworten: q.answers.map( (a, i) => ({
            text: letters[i] + a,
            richtig: correctAnswer === i,
            ausgewählt: selectedAnswer === i,
        }) ),
        tags: _.sampleSize(tags, _.random(1, tags.length))
    }
}

const DummyQuestions = _.take(questions, 80).map( convertQuestion )

export default DummyQuestions