module.exports = {
    "bewertungen": [
        { "epaId": 112, "gemacht": 4, "zutrauen": 5, "fremdbewertungen": [{ "fremdbewertungsId": 3, "wert": 4 }, { "fremdbewertungsId": 4, "wert": 3 }] }, 
        { "epaId": 113, "gemacht": 1, "zutrauen": 4, "fremdbewertungen": [{ "fremdbewertungsId": 4, "wert": 2 }] }, 
        { "epaId": 123, "gemacht": 4, "zutrauen": 2, "fremdbewertungen": [{ "fremdbewertungsId": 4, "wert": 5 }] }, 
        { "epaId": 111, "gemacht": 4, "zutrauen": 5, "fremdbewertungen": [{ "fremdbewertungsId": 3, "wert": 2 }, { "fremdbewertungsId": 4, "wert": 1 }] }, 
        { "epaId": 122, "gemacht": 3, "zutrauen": 1, "fremdbewertungen": null },
        { "epaId": 121, "gemacht": 4, "zutrauen": 2, "fremdbewertungen": null }, 
        { "epaId": 131, "gemacht": 2, "zutrauen": 1, "fremdbewertungen": null }, 
        { "epaId": 132, "gemacht": 1, "zutrauen": 3, "fremdbewertungen": [{ "fremdbewertungsId": 4, "wert": 3 }] }, 
        { "epaId": 512, "gemacht": 0, "zutrauen": 1, "fremdbewertungen": null }, 
        { "epaId": 133, "gemacht": 1, "zutrauen": 1, "fremdbewertungen": null }, 
        { "epaId": 201, "gemacht": 3, "zutrauen": 0, "fremdbewertungen": null }, 
        { "epaId": 202, "gemacht": 1, "zutrauen": 0, "fremdbewertungen": null }, 
        { "epaId": 203, "gemacht": 1, "zutrauen": 0, "fremdbewertungen": null },
        { "epaId": 204, "gemacht": 1, "zutrauen": 1, "fremdbewertungen": null }, 
        { "epaId": 206, "gemacht": 1, "zutrauen": 0, "fremdbewertungen": null }, 
        { "epaId": 141, "gemacht": 1, "zutrauen": 0, "fremdbewertungen": null }, 
        { "epaId": 142, "gemacht": 1, "zutrauen": 0, "fremdbewertungen": null }, 
        { "epaId": 143, "gemacht": 0, "zutrauen": 0, "fremdbewertungen": null }, 
        { "epaId": 411, "gemacht": 1, "zutrauen": 0, "fremdbewertungen": null }, 
        { "epaId": 412, "gemacht": 1, "zutrauen": 1, "fremdbewertungen": null }, 
        { "epaId": 421, "gemacht": 1, "zutrauen": 1, "fremdbewertungen": null }, 
        { "epaId": 422, "gemacht": 1, "zutrauen": 1, "fremdbewertungen": null }, 
        { "epaId": 432, "gemacht": 1, "zutrauen": 1, "fremdbewertungen": null }, 
        { "epaId": 433, "gemacht": 1, "zutrauen": 0, "fremdbewertungen": null }, 
        { "epaId": 205, "gemacht": 0, "zutrauen": 1, "fremdbewertungen": null }, 
        { "epaId": 207, "gemacht": 0, "zutrauen": 1, "fremdbewertungen": null }, 
        { "epaId": 312, "gemacht": 2, "zutrauen": 2, "fremdbewertungen": null }, 
        { "epaId": 311, "gemacht": 1, "zutrauen": 1, "fremdbewertungen": null }, 
        { "epaId": 321, "gemacht": 1, "zutrauen": 1, "fremdbewertungen": null }, 
        { "epaId": 322, "gemacht": 1, "zutrauen": 1, "fremdbewertungen": null }
    ]
}