module.exports = {
    "pruefungen": [
        {
            "name": "Stationspr\u00fcfung Teil3 SoSe2019 Pr\u00fcfungszeitraum 1",
            "typ": "Stat-3",
            "format": "station",
            "fachsemester": 4,
            "studiPruefungsId": 31726,
            "zeitsemester": "SoSe 2019",
            "periodeCode": 201911,
            "periodeText": "SoSe2019 Pr\u00fcfungszeitraum 1",
            "gesamtErgebnis": {
                "ergebnisProzentzahl": 0.86,
                "durchschnittProzentzahl": 0.79
            },
            "stationen": [
                {
                    "code": "00#03",
                    "titel": "KIT Gespr\u00e4chstechnik ",
                    "ergebnisProzentzahl": 0.85,
                    "durchschnittProzentzahl": 0.74
                },
                {
                    "code": "09#01",
                    "titel": "Haut M09",
                    "ergebnisProzentzahl": 0.66,
                    "durchschnittProzentzahl": 0.8
                },
                {
                    "code": "13#02",
                    "titel": "Atmung M13",
                    "ergebnisProzentzahl": 0.93,
                    "durchschnittProzentzahl": 0.82
                },
                {
                    "code": "15#02",
                    "titel": "Nervensystem M15",
                    "ergebnisProzentzahl": 1,
                    "durchschnittProzentzahl": 0.9
                }
            ]
        },
        {
            "name": "Stationspr\u00fcfung Teil1 Vorklinik SoSe2018 Pr\u00fcfungszeitraum 2",
            "typ": "Stat-1VK",
            "format": "station",
            "fachsemester": 2,
            "studiPruefungsId": 29492,
            "zeitsemester": "SoSe 2018",
            "periodeCode": 201812,
            "periodeText": "SoSe2018 Pr\u00fcfungszeitraum 2",
            "gesamtErgebnis": {
                "ergebnisProzentzahl": 0.78,
                "durchschnittProzentzahl": 0.86
            },
            "stationen": [
                {
                    "code": "bioch",
                    "titel": "Biochemie",
                    "ergebnisProzentzahl": 0.85,
                    "details": [
                        {
                            "code": "1",
                            "titel": "Faktenwissen",
                            "ergebnisProzentzahl": 0.83,
                            "durchschnittProzentzahl": 0.75
                        },
                        {
                            "code": "2",
                            "titel": "Zusammenhangswissen",
                            "ergebnisProzentzahl": 0.87,
                            "durchschnittProzentzahl": 0.74
                        }
                    ],
                    "durchschnittProzentzahl": 0.75
                },
                {
                    "code": "sozMed",
                    "titel": "Sozialmedizin",
                    "ergebnisProzentzahl": 0.78,
                    "details": [
                        {
                            "code": "1",
                            "titel": "Faktenwissen",
                            "ergebnisProzentzahl": 0.83,
                            "durchschnittProzentzahl": 0.75
                        },
                        {
                            "code": "2",
                            "titel": "Zusammenhangswissen",
                            "ergebnisProzentzahl": 0.73,
                            "durchschnittProzentzahl": 0.85
                        }
                    ],
                    "durchschnittProzentzahl": 0.80
                }
            ]
        },
        {
            "name": "Stationspr\u00fcfung Teil1 Klinik SoSe2018 Pr\u00fcfungszeitraum 2",
            "typ": "Stat-1K",
            "format": "station",
            "fachsemester": 2,
            "studiPruefungsId": 29573,
            "zeitsemester": "SoSe 2018",
            "periodeCode": 201812,
            "periodeText": "SoSe2018 Pr\u00fcfungszeitraum 2",
            "gesamtErgebnis": {
                "ergebnisProzentzahl": 0.99,
                "durchschnittProzentzahl": 0.87
            },
            "stationen": [
                {
                    "code": "S1#N4",
                    "titel": "Notfallstation",
                    "ergebnisProzentzahl": 1,
                    "durchschnittProzentzahl": 0.89
                },
                {
                    "code": "S1#U2",
                    "titel": "Untersuchungskursstation ",
                    "ergebnisProzentzahl": 0.98,
                    "durchschnittProzentzahl": 0.91
                }
            ]
        },
        {
            "name": "PTM SoSe2019",
            "typ": "PTM",
            "format": "ptm",
            "studiPruefungsId": 22892,
            "zeitsemester": "SoSe 2019",
            "periodeCode": 20191,
            "periodeText": "SoSe2019",
            "gesamtErgebnis": {
                "ergebnisRichtigPunktzahl": 71,
                "ergebnisFalschPunktzahl": 28,
                "ergebnisWeissnichtPunktzahl": 99,
                "durchschnittRichtigPunktzahl": 36,
                "durchschnittFalschPunktzahl": 22,
                "durchschnittWeissnichtPunktzahl": 41,
                "maximalPunktzahl": 198
            },
            "faecher": [
                {
                    "code": "F01",
                    "titel": "Allgemeinmedizin",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 9,
                    "ergebnisFalschPunktzahl": 4,
                    "ergebnisWeissnichtPunktzahl": 4,
                    "durchschnittRichtigPunktzahl": 5,
                    "durchschnittFalschPunktzahl": 2,
                    "durchschnittWeissnichtPunktzahl": 10,
                    "maximalPunktzahl": 17
                },
                {
                    "code": "F02",
                    "titel": "An\u00e4sthesiologie",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 3,
                    "ergebnisFalschPunktzahl": 1,
                    "ergebnisWeissnichtPunktzahl": 4,
                    "durchschnittRichtigPunktzahl": 2,
                    "durchschnittFalschPunktzahl": 1,
                    "durchschnittWeissnichtPunktzahl": 5,
                    "maximalPunktzahl": 8
                },
                {
                    "code": "S03",
                    "titel": "Biologie, Anatomie",
                    "gruppe": "Vorklinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 4,
                    "ergebnisFalschPunktzahl": 1,
                    "ergebnisWeissnichtPunktzahl": 3,
                    "durchschnittRichtigPunktzahl": 2,
                    "durchschnittFalschPunktzahl": 1,
                    "durchschnittWeissnichtPunktzahl": 5,
                    "maximalPunktzahl": 8
                },
                {
                    "code": "F03",
                    "titel": "Arbeitsmedizin, Sozialmedizin",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 1,
                    "ergebnisFalschPunktzahl": 1,
                    "ergebnisWeissnichtPunktzahl": 1,
                    "durchschnittRichtigPunktzahl": 1,
                    "durchschnittFalschPunktzahl": 0,
                    "durchschnittWeissnichtPunktzahl": 2,
                    "maximalPunktzahl": 3
                },
                {
                    "code": "F04",
                    "titel": "Augenheilkunde",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 0,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 2,
                    "durchschnittRichtigPunktzahl": 0,
                    "durchschnittFalschPunktzahl": 0,
                    "durchschnittWeissnichtPunktzahl": 2,
                    "maximalPunktzahl": 2
                },
                {
                    "code": "S02",
                    "titel": "Chemie, Biochemie, Molekurlarbiologie",
                    "gruppe": "Vorklinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 2,
                    "ergebnisFalschPunktzahl": 1,
                    "ergebnisWeissnichtPunktzahl": 1,
                    "durchschnittRichtigPunktzahl": 1,
                    "durchschnittFalschPunktzahl": 0,
                    "durchschnittWeissnichtPunktzahl": 3,
                    "maximalPunktzahl": 4
                },
                {
                    "code": "F05",
                    "titel": "Chirurgie",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 4,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 6,
                    "durchschnittRichtigPunktzahl": 2,
                    "durchschnittFalschPunktzahl": 1,
                    "durchschnittWeissnichtPunktzahl": 7,
                    "maximalPunktzahl": 10
                },
                {
                    "code": "F06",
                    "titel": "Dermatologie, Venerologie",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 0,
                    "ergebnisFalschPunktzahl": 1,
                    "ergebnisWeissnichtPunktzahl": 1,
                    "durchschnittRichtigPunktzahl": 0,
                    "durchschnittFalschPunktzahl": 0,
                    "durchschnittWeissnichtPunktzahl": 2,
                    "maximalPunktzahl": 2
                },
                {
                    "code": "Q01",
                    "titel": "Epidemiologie, medizinische Biometrie und medizinische Informatik",
                    "gruppe": "Querschnittsf\u00e4cher",
                    "ergebnisRichtigPunktzahl": 5,
                    "ergebnisFalschPunktzahl": 1,
                    "ergebnisWeissnichtPunktzahl": 0,
                    "durchschnittRichtigPunktzahl": 2,
                    "durchschnittFalschPunktzahl": 1,
                    "durchschnittWeissnichtPunktzahl": 3,
                    "maximalPunktzahl": 6
                },
                {
                    "code": "F07",
                    "titel": "Frauenheilkunde, Geburtshilfe",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 0,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 5,
                    "durchschnittRichtigPunktzahl": 0,
                    "durchschnittFalschPunktzahl": 0,
                    "durchschnittWeissnichtPunktzahl": 5,
                    "maximalPunktzahl": 5
                },
                {
                    "code": "F08",
                    "titel": "Hals-Nasen-Ohrenheilkunde",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 0,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 6,
                    "durchschnittRichtigPunktzahl": 1,
                    "durchschnittFalschPunktzahl": 1,
                    "durchschnittWeissnichtPunktzahl": 4,
                    "maximalPunktzahl": 6
                },
                {
                    "code": "F09",
                    "titel": "Humangenetik",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 5,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 2,
                    "durchschnittRichtigPunktzahl": 2,
                    "durchschnittFalschPunktzahl": 1,
                    "durchschnittWeissnichtPunktzahl": 4,
                    "maximalPunktzahl": 7
                },
                {
                    "code": "F10",
                    "titel": "Hygiene, Mikrobiologie, Virologie",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 1,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 6,
                    "durchschnittRichtigPunktzahl": 2,
                    "durchschnittFalschPunktzahl": 1,
                    "durchschnittWeissnichtPunktzahl": 4,
                    "maximalPunktzahl": 7
                },
                {
                    "code": "F11",
                    "titel": "Innere Medizin",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 10,
                    "ergebnisFalschPunktzahl": 9,
                    "ergebnisWeissnichtPunktzahl": 17,
                    "durchschnittRichtigPunktzahl": 8,
                    "durchschnittFalschPunktzahl": 4,
                    "durchschnittWeissnichtPunktzahl": 24,
                    "maximalPunktzahl": 36
                },
                {
                    "code": "F12",
                    "titel": "Kinderheilkunde",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 4,
                    "ergebnisFalschPunktzahl": 2,
                    "ergebnisWeissnichtPunktzahl": 7,
                    "durchschnittRichtigPunktzahl": 3,
                    "durchschnittFalschPunktzahl": 1,
                    "durchschnittWeissnichtPunktzahl": 9,
                    "maximalPunktzahl": 13
                },
                {
                    "code": "F13",
                    "titel": "Klinische Chemie, Laboratoriumsdiagnostik",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 0,
                    "ergebnisFalschPunktzahl": 1,
                    "ergebnisWeissnichtPunktzahl": 1,
                    "durchschnittRichtigPunktzahl": 0,
                    "durchschnittFalschPunktzahl": 0,
                    "durchschnittWeissnichtPunktzahl": 2,
                    "maximalPunktzahl": 2
                },
                {
                    "code": "S04",
                    "titel": "Psychologie, Soziologie",
                    "gruppe": "Vorklinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 2,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 1,
                    "durchschnittRichtigPunktzahl": 1,
                    "durchschnittFalschPunktzahl": 0,
                    "durchschnittWeissnichtPunktzahl": 2,
                    "maximalPunktzahl": 3
                },
                {
                    "code": "Q12",
                    "titel": "Rehabilitation, Physikalische Medizin, Naturheilverfahren",
                    "gruppe": "Querschnittsf\u00e4cher",
                    "ergebnisRichtigPunktzahl": 0,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 4,
                    "durchschnittRichtigPunktzahl": 1,
                    "durchschnittFalschPunktzahl": 0,
                    "durchschnittWeissnichtPunktzahl": 3,
                    "maximalPunktzahl": 4
                },
                {
                    "code": "F14",
                    "titel": "Neurologie",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 1,
                    "ergebnisFalschPunktzahl": 1,
                    "ergebnisWeissnichtPunktzahl": 5,
                    "durchschnittRichtigPunktzahl": 1,
                    "durchschnittFalschPunktzahl": 1,
                    "durchschnittWeissnichtPunktzahl": 5,
                    "maximalPunktzahl": 7
                },
                {
                    "code": "F15",
                    "titel": "Orthop\u00e4die",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 2,
                    "ergebnisFalschPunktzahl": 1,
                    "ergebnisWeissnichtPunktzahl": 1,
                    "durchschnittRichtigPunktzahl": 1,
                    "durchschnittFalschPunktzahl": 1,
                    "durchschnittWeissnichtPunktzahl": 2,
                    "maximalPunktzahl": 4
                },
                {
                    "code": "F16",
                    "titel": "Pathologie",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 1,
                    "ergebnisFalschPunktzahl": 1,
                    "ergebnisWeissnichtPunktzahl": 3,
                    "durchschnittRichtigPunktzahl": 1,
                    "durchschnittFalschPunktzahl": 1,
                    "durchschnittWeissnichtPunktzahl": 3,
                    "maximalPunktzahl": 5
                },
                {
                    "code": "F17",
                    "titel": "Pharmakologie, Toxikologie",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 5,
                    "ergebnisFalschPunktzahl": 1,
                    "ergebnisWeissnichtPunktzahl": 6,
                    "durchschnittRichtigPunktzahl": 2,
                    "durchschnittFalschPunktzahl": 1,
                    "durchschnittWeissnichtPunktzahl": 9,
                    "maximalPunktzahl": 12
                },
                {
                    "code": "S01",
                    "titel": "Physik, Physiologie",
                    "gruppe": "Vorklinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 2,
                    "ergebnisFalschPunktzahl": 1,
                    "ergebnisWeissnichtPunktzahl": 6,
                    "durchschnittRichtigPunktzahl": 3,
                    "durchschnittFalschPunktzahl": 1,
                    "durchschnittWeissnichtPunktzahl": 5,
                    "maximalPunktzahl": 9
                },
                {
                    "code": "F18",
                    "titel": "Psychiatrie und Psychotherapie, Psychosomatik",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 6,
                    "ergebnisFalschPunktzahl": 1,
                    "ergebnisWeissnichtPunktzahl": 4,
                    "durchschnittRichtigPunktzahl": 3,
                    "durchschnittFalschPunktzahl": 1,
                    "durchschnittWeissnichtPunktzahl": 7,
                    "maximalPunktzahl": 11
                },
                {
                    "code": "Q11",
                    "titel": "Bildgebende Verfahren, Strahlenbehandlung",
                    "gruppe": "Querschnittsf\u00e4cher",
                    "ergebnisRichtigPunktzahl": 2,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 1,
                    "durchschnittRichtigPunktzahl": 1,
                    "durchschnittFalschPunktzahl": 0,
                    "durchschnittWeissnichtPunktzahl": 2,
                    "maximalPunktzahl": 3
                },
                {
                    "code": "F20",
                    "titel": "Rechtsmedizin",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 2,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 0,
                    "durchschnittRichtigPunktzahl": 1,
                    "durchschnittFalschPunktzahl": 0,
                    "durchschnittWeissnichtPunktzahl": 1,
                    "maximalPunktzahl": 2
                },
                {
                    "code": "F21",
                    "titel": "Urologie",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 0,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 2,
                    "durchschnittRichtigPunktzahl": 1,
                    "durchschnittFalschPunktzahl": 0,
                    "durchschnittWeissnichtPunktzahl": 1,
                    "maximalPunktzahl": 2
                }
            ]
        },
        {
            "name": "PTM WiSe2018",
            "typ": "PTM",
            "format": "ptm",
            "studiPruefungsId": 20495,
            "zeitsemester": "WiSe 2018",
            "periodeCode": 20182,
            "periodeText": "WiSe2018",
            "gesamtErgebnis": {
                "ergebnisRichtigPunktzahl": 47,
                "ergebnisFalschPunktzahl": 26,
                "ergebnisWeissnichtPunktzahl": 24,
                "durchschnittRichtigPunktzahl": 47,
                "durchschnittFalschPunktzahl": 21,
                "durchschnittWeissnichtPunktzahl": 29,
                "maximalPunktzahl": 97
            },
            "faecher": [
                {
                    "code": "F01",
                    "titel": "Allgemeinmedizin",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 4,
                    "ergebnisFalschPunktzahl": 1,
                    "ergebnisWeissnichtPunktzahl": 5,
                    "durchschnittRichtigPunktzahl": 4,
                    "durchschnittFalschPunktzahl": 1,
                    "durchschnittWeissnichtPunktzahl": 5,
                    "maximalPunktzahl": 10
                },
                {
                    "code": "F02",
                    "titel": "An\u00e4sthesiologie",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 3,
                    "ergebnisFalschPunktzahl": 1,
                    "ergebnisWeissnichtPunktzahl": 4,
                    "durchschnittRichtigPunktzahl": 3,
                    "durchschnittFalschPunktzahl": 1,
                    "durchschnittWeissnichtPunktzahl": 4,
                    "maximalPunktzahl": 8
                },
                {
                    "code": "S03",
                    "titel": "Biologie, Anatomie",
                    "gruppe": "Vorklinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 0,
                    "ergebnisFalschPunktzahl": 1,
                    "ergebnisWeissnichtPunktzahl": 13,
                    "durchschnittRichtigPunktzahl": 3,
                    "durchschnittFalschPunktzahl": 1,
                    "durchschnittWeissnichtPunktzahl": 10,
                    "maximalPunktzahl": 14
                },
                {
                    "code": "F03",
                    "titel": "Arbeitsmedizin, Sozialmedizin",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 3,
                    "ergebnisFalschPunktzahl": 1,
                    "ergebnisWeissnichtPunktzahl": 1,
                    "durchschnittRichtigPunktzahl": 2,
                    "durchschnittFalschPunktzahl": 1,
                    "durchschnittWeissnichtPunktzahl": 2,
                    "maximalPunktzahl": 5
                },
                {
                    "code": "F04",
                    "titel": "Augenheilkunde",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 0,
                    "ergebnisFalschPunktzahl": 1,
                    "ergebnisWeissnichtPunktzahl": 2,
                    "durchschnittRichtigPunktzahl": 0,
                    "durchschnittFalschPunktzahl": 1,
                    "durchschnittWeissnichtPunktzahl": 2,
                    "maximalPunktzahl": 3
                },
                {
                    "code": "S02",
                    "titel": "Chemie, Biochemie, Molekurlarbiologie",
                    "gruppe": "Vorklinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 4,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 1,
                    "durchschnittRichtigPunktzahl": 2,
                    "durchschnittFalschPunktzahl": 0,
                    "durchschnittWeissnichtPunktzahl": 3,
                    "maximalPunktzahl": 5
                },
                {
                    "code": "F05",
                    "titel": "Chirurgie",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 2,
                    "ergebnisFalschPunktzahl": 4,
                    "ergebnisWeissnichtPunktzahl": 8,
                    "durchschnittRichtigPunktzahl": 3,
                    "durchschnittFalschPunktzahl": 2,
                    "durchschnittWeissnichtPunktzahl": 9,
                    "maximalPunktzahl": 14
                },
                {
                    "code": "F06",
                    "titel": "Dermatologie, Venerologie",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 0,
                    "ergebnisFalschPunktzahl": 1,
                    "ergebnisWeissnichtPunktzahl": 4,
                    "durchschnittRichtigPunktzahl": 1,
                    "durchschnittFalschPunktzahl": 0,
                    "durchschnittWeissnichtPunktzahl": 4,
                    "maximalPunktzahl": 5
                },
                {
                    "code": "Q01",
                    "titel": "Epidemiologie, medizinische Biometrie und medizinische Informatik",
                    "gruppe": "Querschnittsf\u00e4cher",
                    "ergebnisRichtigPunktzahl": 4,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 3,
                    "durchschnittRichtigPunktzahl": 2,
                    "durchschnittFalschPunktzahl": 1,
                    "durchschnittWeissnichtPunktzahl": 4,
                    "maximalPunktzahl": 7
                },
                {
                    "code": "F07",
                    "titel": "Frauenheilkunde, Geburtshilfe",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 1,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 6,
                    "durchschnittRichtigPunktzahl": 1,
                    "durchschnittFalschPunktzahl": 1,
                    "durchschnittWeissnichtPunktzahl": 5,
                    "maximalPunktzahl": 7
                },
                {
                    "code": "F08",
                    "titel": "Hals-Nasen-Ohrenheilkunde",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 0,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 4,
                    "durchschnittRichtigPunktzahl": 1,
                    "durchschnittFalschPunktzahl": 0,
                    "durchschnittWeissnichtPunktzahl": 3,
                    "maximalPunktzahl": 4
                },
                {
                    "code": "F09",
                    "titel": "Humangenetik",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 3,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 2,
                    "durchschnittRichtigPunktzahl": 1,
                    "durchschnittFalschPunktzahl": 1,
                    "durchschnittWeissnichtPunktzahl": 3,
                    "maximalPunktzahl": 5
                },
                {
                    "code": "F10",
                    "titel": "Hygiene, Mikrobiologie, Virologie",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 1,
                    "ergebnisFalschPunktzahl": 1,
                    "ergebnisWeissnichtPunktzahl": 4,
                    "durchschnittRichtigPunktzahl": 1,
                    "durchschnittFalschPunktzahl": 1,
                    "durchschnittWeissnichtPunktzahl": 4,
                    "maximalPunktzahl": 6
                },
                {
                    "code": "F11",
                    "titel": "Innere Medizin",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 5,
                    "ergebnisFalschPunktzahl": 10,
                    "ergebnisWeissnichtPunktzahl": 21,
                    "durchschnittRichtigPunktzahl": 7,
                    "durchschnittFalschPunktzahl": 4,
                    "durchschnittWeissnichtPunktzahl": 25,
                    "maximalPunktzahl": 36
                },
                {
                    "code": "F12",
                    "titel": "Kinderheilkunde",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 1,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 6,
                    "durchschnittRichtigPunktzahl": 1,
                    "durchschnittFalschPunktzahl": 0,
                    "durchschnittWeissnichtPunktzahl": 6,
                    "maximalPunktzahl": 7
                },
                {
                    "code": "F13",
                    "titel": "Klinische Chemie, Laboratoriumsdiagnostik",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 0,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 2,
                    "durchschnittRichtigPunktzahl": 0,
                    "durchschnittFalschPunktzahl": 0,
                    "durchschnittWeissnichtPunktzahl": 2,
                    "maximalPunktzahl": 2
                },
                {
                    "code": "S04",
                    "titel": "Psychologie, Soziologie",
                    "gruppe": "Vorklinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 2,
                    "ergebnisFalschPunktzahl": 1,
                    "ergebnisWeissnichtPunktzahl": 0,
                    "durchschnittRichtigPunktzahl": 1,
                    "durchschnittFalschPunktzahl": 0,
                    "durchschnittWeissnichtPunktzahl": 2,
                    "maximalPunktzahl": 3
                },
                {
                    "code": "Q12",
                    "titel": "Rehabilitation, Physikalische Medizin, Naturheilverfahren",
                    "gruppe": "Querschnittsf\u00e4cher",
                    "ergebnisRichtigPunktzahl": 1,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 1,
                    "durchschnittRichtigPunktzahl": 0,
                    "durchschnittFalschPunktzahl": 0,
                    "durchschnittWeissnichtPunktzahl": 2,
                    "maximalPunktzahl": 2
                },
                {
                    "code": "F14",
                    "titel": "Neurologie",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 0,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 5,
                    "durchschnittRichtigPunktzahl": 1,
                    "durchschnittFalschPunktzahl": 0,
                    "durchschnittWeissnichtPunktzahl": 4,
                    "maximalPunktzahl": 5
                },
                {
                    "code": "F15",
                    "titel": "Orthop\u00e4die",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 0,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 5,
                    "durchschnittRichtigPunktzahl": 1,
                    "durchschnittFalschPunktzahl": 0,
                    "durchschnittWeissnichtPunktzahl": 4,
                    "maximalPunktzahl": 5
                },
                {
                    "code": "F16",
                    "titel": "Pathologie",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 2,
                    "ergebnisFalschPunktzahl": 1,
                    "ergebnisWeissnichtPunktzahl": 7,
                    "durchschnittRichtigPunktzahl": 3,
                    "durchschnittFalschPunktzahl": 1,
                    "durchschnittWeissnichtPunktzahl": 6,
                    "maximalPunktzahl": 10
                },
                {
                    "code": "F17",
                    "titel": "Pharmakologie, Toxikologie",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 0,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 9,
                    "durchschnittRichtigPunktzahl": 2,
                    "durchschnittFalschPunktzahl": 1,
                    "durchschnittWeissnichtPunktzahl": 6,
                    "maximalPunktzahl": 9
                },
                {
                    "code": "S01",
                    "titel": "Physik, Physiologie",
                    "gruppe": "Vorklinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 1,
                    "ergebnisFalschPunktzahl": 1,
                    "ergebnisWeissnichtPunktzahl": 3,
                    "durchschnittRichtigPunktzahl": 2,
                    "durchschnittFalschPunktzahl": 1,
                    "durchschnittWeissnichtPunktzahl": 2,
                    "maximalPunktzahl": 5
                },
                {
                    "code": "F18",
                    "titel": "Psychiatrie und Psychotherapie, Psychosomatik",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 6,
                    "ergebnisFalschPunktzahl": 2,
                    "ergebnisWeissnichtPunktzahl": 3,
                    "durchschnittRichtigPunktzahl": 3,
                    "durchschnittFalschPunktzahl": 2,
                    "durchschnittWeissnichtPunktzahl": 6,
                    "maximalPunktzahl": 11
                },
                {
                    "code": "Q11",
                    "titel": "Bildgebende Verfahren, Strahlenbehandlung",
                    "gruppe": "Querschnittsf\u00e4cher",
                    "ergebnisRichtigPunktzahl": 1,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 3,
                    "durchschnittRichtigPunktzahl": 1,
                    "durchschnittFalschPunktzahl": 0,
                    "durchschnittWeissnichtPunktzahl": 3,
                    "maximalPunktzahl": 4
                },
                {
                    "code": "F20",
                    "titel": "Rechtsmedizin",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 2,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 0,
                    "durchschnittRichtigPunktzahl": 0,
                    "durchschnittFalschPunktzahl": 0,
                    "durchschnittWeissnichtPunktzahl": 2,
                    "maximalPunktzahl": 2
                },
                {
                    "code": "F21",
                    "titel": "Urologie",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 1,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 2,
                    "durchschnittRichtigPunktzahl": 1,
                    "durchschnittFalschPunktzahl": 0,
                    "durchschnittWeissnichtPunktzahl": 2,
                    "maximalPunktzahl": 3
                }
            ]
        },
        {
            "name": "PTM SoSe2018",
            "typ": "PTM",
            "format": "ptm",
            "studiPruefungsId": 17798,
            "zeitsemester": "SoSe 2018",
            "periodeCode": 20181,
            "periodeText": "SoSe2018",
            "gesamtErgebnis": {
                "ergebnisRichtigPunktzahl": 22,
                "ergebnisFalschPunktzahl": 11,
                "ergebnisWeissnichtPunktzahl": 47,
                "durchschnittRichtigPunktzahl": 36,
                "durchschnittFalschPunktzahl": 19,
                "durchschnittWeissnichtPunktzahl": 25,
                "maximalPunktzahl": 80
            },
            "faecher": [
                {
                    "code": "F01",
                    "titel": "Allgemeinmedizin",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 1,
                    "ergebnisFalschPunktzahl": 2,
                    "ergebnisWeissnichtPunktzahl": 8,
                    "durchschnittRichtigPunktzahl": 3,
                    "durchschnittFalschPunktzahl": 1,
                    "durchschnittWeissnichtPunktzahl": 7,
                    "maximalPunktzahl": 11
                },
                {
                    "code": "F02",
                    "titel": "An\u00e4sthesiologie",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 1,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 6,
                    "durchschnittRichtigPunktzahl": 1,
                    "durchschnittFalschPunktzahl": 1,
                    "durchschnittWeissnichtPunktzahl": 5,
                    "maximalPunktzahl": 7
                },
                {
                    "code": "S03",
                    "titel": "Biologie, Anatomie",
                    "gruppe": "Vorklinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 1,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 6,
                    "durchschnittRichtigPunktzahl": 2,
                    "durchschnittFalschPunktzahl": 1,
                    "durchschnittWeissnichtPunktzahl": 4,
                    "maximalPunktzahl": 7
                },
                {
                    "code": "F03",
                    "titel": "Arbeitsmedizin, Sozialmedizin",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 1,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 2,
                    "durchschnittRichtigPunktzahl": 1,
                    "durchschnittFalschPunktzahl": 0,
                    "durchschnittWeissnichtPunktzahl": 2,
                    "maximalPunktzahl": 3
                },
                {
                    "code": "F04",
                    "titel": "Augenheilkunde",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 0,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 2,
                    "durchschnittRichtigPunktzahl": 0,
                    "durchschnittFalschPunktzahl": 0,
                    "durchschnittWeissnichtPunktzahl": 2,
                    "maximalPunktzahl": 2
                },
                {
                    "code": "S02",
                    "titel": "Chemie, Biochemie, Molekurlarbiologie",
                    "gruppe": "Vorklinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 1,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 3,
                    "durchschnittRichtigPunktzahl": 1,
                    "durchschnittFalschPunktzahl": 0,
                    "durchschnittWeissnichtPunktzahl": 3,
                    "maximalPunktzahl": 4
                },
                {
                    "code": "F05",
                    "titel": "Chirurgie",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 0,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 11,
                    "durchschnittRichtigPunktzahl": 1,
                    "durchschnittFalschPunktzahl": 1,
                    "durchschnittWeissnichtPunktzahl": 9,
                    "maximalPunktzahl": 11
                },
                {
                    "code": "F06",
                    "titel": "Dermatologie, Venerologie",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 0,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 4,
                    "durchschnittRichtigPunktzahl": 1,
                    "durchschnittFalschPunktzahl": 0,
                    "durchschnittWeissnichtPunktzahl": 3,
                    "maximalPunktzahl": 4
                },
                {
                    "code": "Q01",
                    "titel": "Epidemiologie, medizinische Biometrie und medizinische Informatik",
                    "gruppe": "Querschnittsf\u00e4cher",
                    "ergebnisRichtigPunktzahl": 0,
                    "ergebnisFalschPunktzahl": 1,
                    "ergebnisWeissnichtPunktzahl": 3,
                    "durchschnittRichtigPunktzahl": 1,
                    "durchschnittFalschPunktzahl": 0,
                    "durchschnittWeissnichtPunktzahl": 3,
                    "maximalPunktzahl": 4
                },
                {
                    "code": "F07",
                    "titel": "Frauenheilkunde, Geburtshilfe",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 2,
                    "ergebnisFalschPunktzahl": 1,
                    "ergebnisWeissnichtPunktzahl": 9,
                    "durchschnittRichtigPunktzahl": 1,
                    "durchschnittFalschPunktzahl": 1,
                    "durchschnittWeissnichtPunktzahl": 10,
                    "maximalPunktzahl": 12
                },
                {
                    "code": "F08",
                    "titel": "Hals-Nasen-Ohrenheilkunde",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 0,
                    "ergebnisFalschPunktzahl": 1,
                    "ergebnisWeissnichtPunktzahl": 3,
                    "durchschnittRichtigPunktzahl": 1,
                    "durchschnittFalschPunktzahl": 1,
                    "durchschnittWeissnichtPunktzahl": 2,
                    "maximalPunktzahl": 4
                },
                {
                    "code": "F09",
                    "titel": "Humangenetik",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 1,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 3,
                    "durchschnittRichtigPunktzahl": 1,
                    "durchschnittFalschPunktzahl": 0,
                    "durchschnittWeissnichtPunktzahl": 3,
                    "maximalPunktzahl": 4
                },
                {
                    "code": "F10",
                    "titel": "Hygiene, Mikrobiologie, Virologie",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 0,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 5,
                    "durchschnittRichtigPunktzahl": 2,
                    "durchschnittFalschPunktzahl": 0,
                    "durchschnittWeissnichtPunktzahl": 3,
                    "maximalPunktzahl": 5
                },
                {
                    "code": "F11",
                    "titel": "Innere Medizin",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 2,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 27,
                    "durchschnittRichtigPunktzahl": 5,
                    "durchschnittFalschPunktzahl": 3,
                    "durchschnittWeissnichtPunktzahl": 21,
                    "maximalPunktzahl": 29
                },
                {
                    "code": "F12",
                    "titel": "Kinderheilkunde",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 3,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 7,
                    "durchschnittRichtigPunktzahl": 2,
                    "durchschnittFalschPunktzahl": 1,
                    "durchschnittWeissnichtPunktzahl": 7,
                    "maximalPunktzahl": 10
                },
                {
                    "code": "F13",
                    "titel": "Klinische Chemie, Laboratoriumsdiagnostik",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 0,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 1,
                    "durchschnittRichtigPunktzahl": 0,
                    "durchschnittFalschPunktzahl": 0,
                    "durchschnittWeissnichtPunktzahl": 1,
                    "maximalPunktzahl": 1
                },
                {
                    "code": "S04",
                    "titel": "Psychologie, Soziologie",
                    "gruppe": "Vorklinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 3,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 1,
                    "durchschnittRichtigPunktzahl": 1,
                    "durchschnittFalschPunktzahl": 1,
                    "durchschnittWeissnichtPunktzahl": 2,
                    "maximalPunktzahl": 4
                },
                {
                    "code": "Q12",
                    "titel": "Rehabilitation, Physikalische Medizin, Naturheilverfahren",
                    "gruppe": "Querschnittsf\u00e4cher",
                    "ergebnisRichtigPunktzahl": 2,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 0,
                    "durchschnittRichtigPunktzahl": 1,
                    "durchschnittFalschPunktzahl": 0,
                    "durchschnittWeissnichtPunktzahl": 1,
                    "maximalPunktzahl": 2
                },
                {
                    "code": "F14",
                    "titel": "Neurologie",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 1,
                    "ergebnisFalschPunktzahl": 2,
                    "ergebnisWeissnichtPunktzahl": 5,
                    "durchschnittRichtigPunktzahl": 2,
                    "durchschnittFalschPunktzahl": 1,
                    "durchschnittWeissnichtPunktzahl": 5,
                    "maximalPunktzahl": 8
                },
                {
                    "code": "F15",
                    "titel": "Orthop\u00e4die",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 0,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 5,
                    "durchschnittRichtigPunktzahl": 1,
                    "durchschnittFalschPunktzahl": 0,
                    "durchschnittWeissnichtPunktzahl": 4,
                    "maximalPunktzahl": 5
                },
                {
                    "code": "F16",
                    "titel": "Pathologie",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 1,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 5,
                    "durchschnittRichtigPunktzahl": 1,
                    "durchschnittFalschPunktzahl": 0,
                    "durchschnittWeissnichtPunktzahl": 5,
                    "maximalPunktzahl": 6
                },
                {
                    "code": "F17",
                    "titel": "Pharmakologie, Toxikologie",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 0,
                    "ergebnisFalschPunktzahl": 2,
                    "ergebnisWeissnichtPunktzahl": 7,
                    "durchschnittRichtigPunktzahl": 1,
                    "durchschnittFalschPunktzahl": 1,
                    "durchschnittWeissnichtPunktzahl": 7,
                    "maximalPunktzahl": 9
                },
                {
                    "code": "S01",
                    "titel": "Physik, Physiologie",
                    "gruppe": "Vorklinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 0,
                    "ergebnisFalschPunktzahl": 1,
                    "ergebnisWeissnichtPunktzahl": 8,
                    "durchschnittRichtigPunktzahl": 2,
                    "durchschnittFalschPunktzahl": 1,
                    "durchschnittWeissnichtPunktzahl": 6,
                    "maximalPunktzahl": 9
                },
                {
                    "code": "F18",
                    "titel": "Psychiatrie und Psychotherapie, Psychosomatik",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 2,
                    "ergebnisFalschPunktzahl": 1,
                    "ergebnisWeissnichtPunktzahl": 7,
                    "durchschnittRichtigPunktzahl": 2,
                    "durchschnittFalschPunktzahl": 1,
                    "durchschnittWeissnichtPunktzahl": 7,
                    "maximalPunktzahl": 10
                },
                {
                    "code": "Q11",
                    "titel": "Bildgebende Verfahren, Strahlenbehandlung",
                    "gruppe": "Querschnittsf\u00e4cher",
                    "ergebnisRichtigPunktzahl": 0,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 4,
                    "durchschnittRichtigPunktzahl": 1,
                    "durchschnittFalschPunktzahl": 0,
                    "durchschnittWeissnichtPunktzahl": 3,
                    "maximalPunktzahl": 4
                },
                {
                    "code": "F20",
                    "titel": "Rechtsmedizin",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 0,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 2,
                    "durchschnittRichtigPunktzahl": 0,
                    "durchschnittFalschPunktzahl": 0,
                    "durchschnittWeissnichtPunktzahl": 2,
                    "maximalPunktzahl": 2
                },
                {
                    "code": "F21",
                    "titel": "Urologie",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 0,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 3,
                    "durchschnittRichtigPunktzahl": 0,
                    "durchschnittFalschPunktzahl": 0,
                    "durchschnittWeissnichtPunktzahl": 3,
                    "maximalPunktzahl": 3
                }
            ]
        },
        {
            "name": "PTM WiSe2017",
            "typ": "PTM",
            "format": "ptm",
            "studiPruefungsId": 15850,
            "zeitsemester": "WiSe 2017",
            "periodeCode": 20172,
            "periodeText": "WiSe2017",
            "gesamtErgebnis": {
                "ergebnisRichtigPunktzahl": 20,
                "ergebnisFalschPunktzahl": 9,
                "ergebnisWeissnichtPunktzahl": 70,
                "durchschnittRichtigPunktzahl": 35,
                "durchschnittFalschPunktzahl": 19,
                "durchschnittWeissnichtPunktzahl": 45,
                "maximalPunktzahl": 99
            },
            "faecher": [
                {
                    "code": "F01",
                    "titel": "Allgemeinmedizin",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 2,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 14,
                    "durchschnittRichtigPunktzahl": 4,
                    "durchschnittFalschPunktzahl": 2,
                    "durchschnittWeissnichtPunktzahl": 10,
                    "maximalPunktzahl": 16
                },
                {
                    "code": "F02",
                    "titel": "An\u00e4sthesiologie",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 1,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 7,
                    "durchschnittRichtigPunktzahl": 1,
                    "durchschnittFalschPunktzahl": 1,
                    "durchschnittWeissnichtPunktzahl": 6,
                    "maximalPunktzahl": 8
                },
                {
                    "code": "S03",
                    "titel": "Biologie, Anatomie",
                    "gruppe": "Vorklinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 2,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 10,
                    "durchschnittRichtigPunktzahl": 3,
                    "durchschnittFalschPunktzahl": 1,
                    "durchschnittWeissnichtPunktzahl": 8,
                    "maximalPunktzahl": 12
                },
                {
                    "code": "F03",
                    "titel": "Arbeitsmedizin, Sozialmedizin",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 0,
                    "ergebnisFalschPunktzahl": 1,
                    "ergebnisWeissnichtPunktzahl": 3,
                    "durchschnittRichtigPunktzahl": 1,
                    "durchschnittFalschPunktzahl": 1,
                    "durchschnittWeissnichtPunktzahl": 2,
                    "maximalPunktzahl": 4
                },
                {
                    "code": "F04",
                    "titel": "Augenheilkunde",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 0,
                    "ergebnisFalschPunktzahl": 1,
                    "ergebnisWeissnichtPunktzahl": 2,
                    "durchschnittRichtigPunktzahl": 0,
                    "durchschnittFalschPunktzahl": 0,
                    "durchschnittWeissnichtPunktzahl": 3,
                    "maximalPunktzahl": 3
                },
                {
                    "code": "S02",
                    "titel": "Chemie, Biochemie, Molekurlarbiologie",
                    "gruppe": "Vorklinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 3,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 4,
                    "durchschnittRichtigPunktzahl": 3,
                    "durchschnittFalschPunktzahl": 1,
                    "durchschnittWeissnichtPunktzahl": 3,
                    "maximalPunktzahl": 7
                },
                {
                    "code": "F05",
                    "titel": "Chirurgie",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 0,
                    "ergebnisFalschPunktzahl": 1,
                    "ergebnisWeissnichtPunktzahl": 10,
                    "durchschnittRichtigPunktzahl": 2,
                    "durchschnittFalschPunktzahl": 1,
                    "durchschnittWeissnichtPunktzahl": 8,
                    "maximalPunktzahl": 11
                },
                {
                    "code": "F06",
                    "titel": "Dermatologie, Venerologie",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 0,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 4,
                    "durchschnittRichtigPunktzahl": 1,
                    "durchschnittFalschPunktzahl": 1,
                    "durchschnittWeissnichtPunktzahl": 2,
                    "maximalPunktzahl": 4
                },
                {
                    "code": "Q01",
                    "titel": "Epidemiologie, medizinische Biometrie und medizinische Informatik",
                    "gruppe": "Querschnittsf\u00e4cher",
                    "ergebnisRichtigPunktzahl": 1,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 3,
                    "durchschnittRichtigPunktzahl": 1,
                    "durchschnittFalschPunktzahl": 1,
                    "durchschnittWeissnichtPunktzahl": 2,
                    "maximalPunktzahl": 4
                },
                {
                    "code": "F07",
                    "titel": "Frauenheilkunde, Geburtshilfe",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 1,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 6,
                    "durchschnittRichtigPunktzahl": 1,
                    "durchschnittFalschPunktzahl": 0,
                    "durchschnittWeissnichtPunktzahl": 6,
                    "maximalPunktzahl": 7
                },
                {
                    "code": "F08",
                    "titel": "Hals-Nasen-Ohrenheilkunde",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 0,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 2,
                    "durchschnittRichtigPunktzahl": 0,
                    "durchschnittFalschPunktzahl": 0,
                    "durchschnittWeissnichtPunktzahl": 2,
                    "maximalPunktzahl": 2
                },
                {
                    "code": "F09",
                    "titel": "Humangenetik",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 1,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 3,
                    "durchschnittRichtigPunktzahl": 0,
                    "durchschnittFalschPunktzahl": 1,
                    "durchschnittWeissnichtPunktzahl": 3,
                    "maximalPunktzahl": 4
                },
                {
                    "code": "F10",
                    "titel": "Hygiene, Mikrobiologie, Virologie",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 1,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 5,
                    "durchschnittRichtigPunktzahl": 1,
                    "durchschnittFalschPunktzahl": 0,
                    "durchschnittWeissnichtPunktzahl": 5,
                    "maximalPunktzahl": 6
                },
                {
                    "code": "F11",
                    "titel": "Innere Medizin",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 2,
                    "ergebnisFalschPunktzahl": 1,
                    "ergebnisWeissnichtPunktzahl": 26,
                    "durchschnittRichtigPunktzahl": 4,
                    "durchschnittFalschPunktzahl": 3,
                    "durchschnittWeissnichtPunktzahl": 22,
                    "maximalPunktzahl": 29
                },
                {
                    "code": "F12",
                    "titel": "Kinderheilkunde",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 0,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 11,
                    "durchschnittRichtigPunktzahl": 1,
                    "durchschnittFalschPunktzahl": 1,
                    "durchschnittWeissnichtPunktzahl": 9,
                    "maximalPunktzahl": 11
                },
                {
                    "code": "F13",
                    "titel": "Klinische Chemie, Laboratoriumsdiagnostik",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 0,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 1,
                    "durchschnittRichtigPunktzahl": 0,
                    "durchschnittFalschPunktzahl": 0,
                    "durchschnittWeissnichtPunktzahl": 1,
                    "maximalPunktzahl": 1
                },
                {
                    "code": "S04",
                    "titel": "Psychologie, Soziologie",
                    "gruppe": "Vorklinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 1,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 2,
                    "durchschnittRichtigPunktzahl": 0,
                    "durchschnittFalschPunktzahl": 1,
                    "durchschnittWeissnichtPunktzahl": 2,
                    "maximalPunktzahl": 3
                },
                {
                    "code": "Q12",
                    "titel": "Rehabilitation, Physikalische Medizin, Naturheilverfahren",
                    "gruppe": "Querschnittsf\u00e4cher",
                    "ergebnisRichtigPunktzahl": 0,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 1,
                    "durchschnittRichtigPunktzahl": 0,
                    "durchschnittFalschPunktzahl": 0,
                    "durchschnittWeissnichtPunktzahl": 1,
                    "maximalPunktzahl": 1
                },
                {
                    "code": "F14",
                    "titel": "Neurologie",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 0,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 7,
                    "durchschnittRichtigPunktzahl": 1,
                    "durchschnittFalschPunktzahl": 1,
                    "durchschnittWeissnichtPunktzahl": 5,
                    "maximalPunktzahl": 7
                },
                {
                    "code": "F15",
                    "titel": "Orthop\u00e4die",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 0,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 5,
                    "durchschnittRichtigPunktzahl": 1,
                    "durchschnittFalschPunktzahl": 0,
                    "durchschnittWeissnichtPunktzahl": 4,
                    "maximalPunktzahl": 5
                },
                {
                    "code": "F16",
                    "titel": "Pathologie",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 0,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 10,
                    "durchschnittRichtigPunktzahl": 2,
                    "durchschnittFalschPunktzahl": 1,
                    "durchschnittWeissnichtPunktzahl": 7,
                    "maximalPunktzahl": 10
                },
                {
                    "code": "F17",
                    "titel": "Pharmakologie, Toxikologie",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 0,
                    "ergebnisFalschPunktzahl": 1,
                    "ergebnisWeissnichtPunktzahl": 9,
                    "durchschnittRichtigPunktzahl": 1,
                    "durchschnittFalschPunktzahl": 0,
                    "durchschnittWeissnichtPunktzahl": 9,
                    "maximalPunktzahl": 10
                },
                {
                    "code": "S01",
                    "titel": "Physik, Physiologie",
                    "gruppe": "Vorklinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 0,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 11,
                    "durchschnittRichtigPunktzahl": 2,
                    "durchschnittFalschPunktzahl": 1,
                    "durchschnittWeissnichtPunktzahl": 8,
                    "maximalPunktzahl": 11
                },
                {
                    "code": "F18",
                    "titel": "Psychiatrie und Psychotherapie, Psychosomatik",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 4,
                    "ergebnisFalschPunktzahl": 3,
                    "ergebnisWeissnichtPunktzahl": 4,
                    "durchschnittRichtigPunktzahl": 2,
                    "durchschnittFalschPunktzahl": 1,
                    "durchschnittWeissnichtPunktzahl": 8,
                    "maximalPunktzahl": 11
                },
                {
                    "code": "Q11",
                    "titel": "Bildgebende Verfahren, Strahlenbehandlung",
                    "gruppe": "Querschnittsf\u00e4cher",
                    "ergebnisRichtigPunktzahl": 0,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 4,
                    "durchschnittRichtigPunktzahl": 1,
                    "durchschnittFalschPunktzahl": 0,
                    "durchschnittWeissnichtPunktzahl": 3,
                    "maximalPunktzahl": 4
                },
                {
                    "code": "F20",
                    "titel": "Rechtsmedizin",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 1,
                    "ergebnisFalschPunktzahl": 0,
                    "ergebnisWeissnichtPunktzahl": 1,
                    "durchschnittRichtigPunktzahl": 1,
                    "durchschnittFalschPunktzahl": 0,
                    "durchschnittWeissnichtPunktzahl": 1,
                    "maximalPunktzahl": 2
                },
                {
                    "code": "F21",
                    "titel": "Urologie",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisRichtigPunktzahl": 0,
                    "ergebnisFalschPunktzahl": 1,
                    "ergebnisWeissnichtPunktzahl": 5,
                    "durchschnittRichtigPunktzahl": 1,
                    "durchschnittFalschPunktzahl": 0,
                    "durchschnittWeissnichtPunktzahl": 5,
                    "maximalPunktzahl": 6
                }
            ]
        },
        {
            "name": "MC-Test Sem.3 WiSe2018 Pr\u00fcfungszeitraum 2",
            "typ": "MC-Sem3",
            "format": "mc",
            "studiPruefungsId": 2207,
            "zeitsemester": "WiSe 2018",
            "periodeCode": 201822,
            "periodeText": "WiSe2018 Pr\u00fcfungszeitraum 2",
            "gesamtErgebnis": {
                "ergebnisPunktzahl": 70,
                "durchschnittsPunktzahl": 61.27,
                "maximalPunktzahl": 99,
                "bestehensgrenzePunktzahl": 52,
                "kohortenPunktzahlen": [
                    59,
                    63,
                    61,
                    48,
                    61,
                    79,
                    51,
                    41,
                    43,
                    74,
                    53,
                    37,
                    67,
                    58,
                    53,
                    41,
                    65,
                    77,
                    56,
                    65,
                    44,
                    51,
                    77,
                    61,
                    77,
                    52,
                    41,
                    68,
                    66,
                    46,
                    65,
                    65,
                    60,
                    79,
                    71,
                    36,
                    69,
                    60,
                    76,
                    72,
                    63,
                    74,
                    83,
                    70,
                    34,
                    59,
                    75,
                    69,
                    66,
                    63,
                    70,
                    83,
                    64,
                    67,
                    42
                ]
            },
            "faecher": [
                {
                    "code": "S03",
                    "titel": "Biologie, Anatomie",
                    "gruppe": "Vorklinische F\u00e4cher",
                    "ergebnisPunktzahl": 15,
                    "durchschnittsPunktzahl": 14.58,
                    "maximalPunktzahl": 22
                },
                {
                    "code": "F11",
                    "titel": "Innere Medizin",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisPunktzahl": 7,
                    "durchschnittsPunktzahl": 5.79,
                    "maximalPunktzahl": 8
                },
                {
                    "code": "S02",
                    "titel": "Chemie, Biochemie, Molekurlarbiologie",
                    "gruppe": "Vorklinische F\u00e4cher",
                    "ergebnisPunktzahl": 6,
                    "durchschnittsPunktzahl": 6.38,
                    "maximalPunktzahl": 9
                },
                {
                    "code": "S01",
                    "titel": "Physik, Physiologie",
                    "gruppe": "Vorklinische F\u00e4cher",
                    "ergebnisPunktzahl": 16,
                    "durchschnittsPunktzahl": 13.6,
                    "maximalPunktzahl": 23
                },
                {
                    "code": "F13",
                    "titel": "Klinische Chemie, Laboratoriumsdiagnostik",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisPunktzahl": 0,
                    "durchschnittsPunktzahl": 0.22,
                    "maximalPunktzahl": 1
                },
                {
                    "code": "F06",
                    "titel": "Dermatologie, Venerologie",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisPunktzahl": 6,
                    "durchschnittsPunktzahl": 5.74,
                    "maximalPunktzahl": 8
                },
                {
                    "code": "F10",
                    "titel": "Hygiene, Mikrobiologie, Virologie",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisPunktzahl": 3,
                    "durchschnittsPunktzahl": 2.4,
                    "maximalPunktzahl": 3
                },
                {
                    "code": "F15",
                    "titel": "Orthop\u00e4die",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisPunktzahl": 1,
                    "durchschnittsPunktzahl": 0.98,
                    "maximalPunktzahl": 2
                },
                {
                    "code": "F02",
                    "titel": "An\u00e4sthesiologie",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisPunktzahl": 1,
                    "durchschnittsPunktzahl": 0.71,
                    "maximalPunktzahl": 1
                },
                {
                    "code": "F03",
                    "titel": "Arbeitsmedizin, Sozialmedizin",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisPunktzahl": 1,
                    "durchschnittsPunktzahl": 0.11,
                    "maximalPunktzahl": 1
                },
                {
                    "code": "F08",
                    "titel": "Hals-Nasen-Ohrenheilkunde",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisPunktzahl": 1,
                    "durchschnittsPunktzahl": 0.85,
                    "maximalPunktzahl": 1
                }
            ],
            "module": [
                {
                    "code": "M10",
                    "titel": "Modul 10",
                    "ergebnisPunktzahl": 0.7,
                    "durchschnittsPunktzahl": 0.63,
                    "maximalPunktzahl": 1
                },
                {
                    "code": "M11",
                    "titel": "Modul 11",
                    "ergebnisPunktzahl": 0.84,
                    "durchschnittsPunktzahl": 0.61,
                    "maximalPunktzahl": 1
                },
                {
                    "code": "M12",
                    "titel": "Modul 12",
                    "ergebnisPunktzahl": 0.6,
                    "durchschnittsPunktzahl": 0.63,
                    "maximalPunktzahl": 1
                },
                {
                    "code": "M09",
                    "titel": "Modul 9",
                    "ergebnisPunktzahl": 0.75,
                    "durchschnittsPunktzahl": 0.73,
                    "maximalPunktzahl": 1
                }
            ]
        },
        {
            "name": "MC-Test Sem.2 SoSe2018 Pr\u00fcfungszeitraum 1",
            "typ": "MC-Sem2",
            "format": "mc",
            "studiPruefungsId": 2850,
            "zeitsemester": "SoSe 2018",
            "periodeCode": 201811,
            "periodeText": "SoSe2018 Pr\u00fcfungszeitraum 1",
            "gesamtErgebnis": {
                "ergebnisPunktzahl": 66,
                "durchschnittsPunktzahl": 58.74,
                "maximalPunktzahl": 76,
                "bestehensgrenzePunktzahl": 46,
                "kohortenPunktzahlen": [
                    61,
                    56,
                    62,
                    61,
                    43,
                    59,
                    49,
                    63,
                    55,
                    54,
                    63,
                    56,
                    56,
                    66,
                    66,
                    52,
                    72,
                    63,
                    58,
                    61,
                    61,
                    61,
                    68,
                    45,
                    62,
                    60,
                    51,
                    58,
                    64,
                    49,
                    47,
                    57,
                    62,
                    65,
                    61,
                    60,
                    51,
                    58,
                    47,
                    71,
                    57,
                    57,
                    48,
                    55,
                    66,
                    50,
                    61,
                    50,
                    60,
                    52,
                    61,
                    64,
                    33,
                    50,
                    58,
                    55,
                    52,
                    58,
                    65,
                    66,
                    56,
                    55,
                    62,
                    56,
                    56,
                    64,
                    56,
                    63,
                    65,
                    62,
                    58,
                    64,
                    53,
                    55,
                    64,
                    57,
                    71,
                    47,
                    44,
                    58,
                    73,
                    57,
                    63,
                    50,
                    39,
                    68,
                    64,
                    68,
                    48,
                    53,
                    65,
                    61,
                    60,
                    62,
                    62,
                    55,
                    56,
                    55,
                    65,
                    61,
                    57,
                    58,
                    63,
                    65,
                    56,
                    62,
                    53,
                    61,
                    35,
                    37,
                    53,
                    57,
                    67,
                    63,
                    57,
                    60,
                    58,
                    52,
                    64,
                    55,
                    68,
                    56,
                    53,
                    67,
                    67,
                    56,
                    63,
                    59,
                    63,
                    68,
                    65,
                    68,
                    57,
                    32,
                    52,
                    56,
                    60,
                    60,
                    66,
                    61,
                    50,
                    61,
                    52,
                    62,
                    60,
                    58,
                    59,
                    59,
                    63,
                    53,
                    67,
                    65,
                    49,
                    67,
                    50,
                    63,
                    38,
                    55,
                    52,
                    54,
                    56,
                    60,
                    58,
                    62,
                    41,
                    64,
                    65,
                    55,
                    68,
                    38,
                    64,
                    52,
                    55,
                    64,
                    64,
                    64,
                    56,
                    64,
                    65,
                    60,
                    65,
                    66,
                    66,
                    57,
                    55,
                    61,
                    64,
                    52,
                    67,
                    61,
                    67,
                    47,
                    58,
                    72,
                    64,
                    58,
                    64,
                    62,
                    64,
                    70,
                    59,
                    50,
                    54,
                    61,
                    57,
                    68,
                    60,
                    64,
                    61,
                    62,
                    67,
                    48,
                    47,
                    63,
                    62,
                    51,
                    51,
                    50,
                    55,
                    61,
                    65,
                    64,
                    61,
                    58,
                    50,
                    62,
                    59,
                    64,
                    65,
                    61,
                    61,
                    58,
                    67,
                    64,
                    61,
                    61,
                    56,
                    59,
                    58,
                    60,
                    58,
                    60,
                    50,
                    67,
                    55,
                    69,
                    67,
                    53,
                    70,
                    50,
                    66,
                    56,
                    60,
                    54,
                    64,
                    66,
                    62,
                    64,
                    70,
                    58,
                    64,
                    61,
                    42,
                    61,
                    56,
                    66,
                    65,
                    68,
                    60,
                    65,
                    44,
                    54,
                    61
                ]
            },
            "faecher": [
                {
                    "code": "A",
                    "titel": "Anderes",
                    "gruppe": "Andere",
                    "ergebnisPunktzahl": 7,
                    "durchschnittsPunktzahl": 6.58,
                    "maximalPunktzahl": 9
                },
                {
                    "code": "S03",
                    "titel": "Biologie, Anatomie",
                    "gruppe": "Vorklinische F\u00e4cher",
                    "ergebnisPunktzahl": 10,
                    "durchschnittsPunktzahl": 9.49,
                    "maximalPunktzahl": 11
                },
                {
                    "code": "F13",
                    "titel": "Klinische Chemie, Laboratoriumsdiagnostik",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisPunktzahl": 1,
                    "durchschnittsPunktzahl": 0.88,
                    "maximalPunktzahl": 1
                },
                {
                    "code": "S02",
                    "titel": "Chemie, Biochemie, Molekurlarbiologie",
                    "gruppe": "Vorklinische F\u00e4cher",
                    "ergebnisPunktzahl": 8,
                    "durchschnittsPunktzahl": 5.37,
                    "maximalPunktzahl": 8
                },
                {
                    "code": "F18",
                    "titel": "Psychiatrie und Psychotherapie, Psychosomatik",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisPunktzahl": 1,
                    "durchschnittsPunktzahl": 0.95,
                    "maximalPunktzahl": 1
                },
                {
                    "code": "S04",
                    "titel": "Psychologie, Soziologie",
                    "gruppe": "Vorklinische F\u00e4cher",
                    "ergebnisPunktzahl": 12,
                    "durchschnittsPunktzahl": 10.46,
                    "maximalPunktzahl": 14
                },
                {
                    "code": "F03",
                    "titel": "Arbeitsmedizin, Sozialmedizin",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisPunktzahl": 5,
                    "durchschnittsPunktzahl": 4.76,
                    "maximalPunktzahl": 5
                },
                {
                    "code": "F16",
                    "titel": "Pathologie",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisPunktzahl": 2,
                    "durchschnittsPunktzahl": 1.08,
                    "maximalPunktzahl": 2
                },
                {
                    "code": "F11",
                    "titel": "Innere Medizin",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisPunktzahl": 2,
                    "durchschnittsPunktzahl": 1.79,
                    "maximalPunktzahl": 3
                },
                {
                    "code": "S01",
                    "titel": "Physik, Physiologie",
                    "gruppe": "Vorklinische F\u00e4cher",
                    "ergebnisPunktzahl": 4,
                    "durchschnittsPunktzahl": 3.25,
                    "maximalPunktzahl": 4
                },
                {
                    "code": "Q01",
                    "titel": "Epidemiologie, medizinische Biometrie und medizinische Informatik",
                    "gruppe": "Querschnittsf\u00e4cher",
                    "ergebnisPunktzahl": 11,
                    "durchschnittsPunktzahl": 10.87,
                    "maximalPunktzahl": 14
                },
                {
                    "code": "F12",
                    "titel": "Kinderheilkunde",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisPunktzahl": 2,
                    "durchschnittsPunktzahl": 1.68,
                    "maximalPunktzahl": 2
                },
                {
                    "code": "F06",
                    "titel": "Dermatologie, Venerologie",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisPunktzahl": 1,
                    "durchschnittsPunktzahl": 0.88,
                    "maximalPunktzahl": 1
                },
                {
                    "code": "F09",
                    "titel": "Humangenetik",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisPunktzahl": 0,
                    "durchschnittsPunktzahl": 0.64,
                    "maximalPunktzahl": 1
                }
            ],
            "module": [
                {
                    "code": "M08",
                    "titel": "Modul 8",
                    "ergebnisPunktzahl": 0.83,
                    "durchschnittsPunktzahl": 0.73,
                    "maximalPunktzahl": 1
                },
                {
                    "code": "M05",
                    "titel": "Modul 5",
                    "ergebnisPunktzahl": 0.89,
                    "durchschnittsPunktzahl": 0.77,
                    "maximalPunktzahl": 1
                },
                {
                    "code": "M06",
                    "titel": "Modul 6",
                    "ergebnisPunktzahl": 0.95,
                    "durchschnittsPunktzahl": 0.82,
                    "maximalPunktzahl": 1
                },
                {
                    "code": "M07",
                    "titel": "Modul 7",
                    "ergebnisPunktzahl": 0.8,
                    "durchschnittsPunktzahl": 0.77,
                    "maximalPunktzahl": 1
                }
            ]
        },
        {
            "name": "MC-Test Sem.1 WiSe2017 Pr\u00fcfungszeitraum 1",
            "typ": "MC-Sem1",
            "format": "mc",
            "studiPruefungsId": 4803,
            "zeitsemester": "WiSe 2017",
            "periodeCode": 201721,
            "periodeText": "WiSe2017 Pr\u00fcfungszeitraum 1",
            "gesamtErgebnis": {
                "ergebnisPunktzahl": 54,
                "durchschnittsPunktzahl": 44.5,
                "maximalPunktzahl": 58,
                "bestehensgrenzePunktzahl": 35,
                "kohortenPunktzahlen": [
                    46,
                    52,
                    52,
                    41,
                    45,
                    48,
                    47,
                    44,
                    46,
                    45,
                    47,
                    34,
                    44,
                    48,
                    26,
                    52,
                    36,
                    41,
                    26,
                    51,
                    49,
                    48,
                    52,
                    53,
                    42,
                    25,
                    44,
                    49,
                    50,
                    46,
                    53,
                    43,
                    33,
                    45,
                    54,
                    43,
                    53,
                    44,
                    49,
                    39,
                    44,
                    35,
                    48,
                    47,
                    46,
                    45,
                    44,
                    43,
                    54,
                    46,
                    51,
                    47,
                    44,
                    39,
                    42,
                    40,
                    51,
                    44,
                    41,
                    48,
                    47,
                    34,
                    53,
                    37,
                    44,
                    46,
                    50,
                    32,
                    29,
                    54,
                    40,
                    48,
                    51,
                    40,
                    53,
                    50,
                    53,
                    42,
                    54,
                    50,
                    33,
                    51,
                    45,
                    56,
                    50,
                    49,
                    41,
                    35,
                    51,
                    23,
                    45,
                    51,
                    39,
                    53,
                    43,
                    50,
                    38,
                    35,
                    53,
                    44,
                    24,
                    35,
                    52,
                    51,
                    39,
                    48,
                    49,
                    44,
                    41,
                    41,
                    39,
                    30,
                    35,
                    56,
                    29,
                    19,
                    48,
                    40,
                    48,
                    49,
                    46,
                    47,
                    24,
                    46,
                    51,
                    34,
                    50,
                    25,
                    36,
                    49,
                    48,
                    17,
                    44,
                    42,
                    54,
                    50,
                    44,
                    44,
                    48,
                    46,
                    46,
                    49,
                    51,
                    54,
                    33,
                    44,
                    33,
                    55,
                    56,
                    49,
                    50,
                    32,
                    54,
                    49,
                    37,
                    52,
                    47,
                    55,
                    40,
                    50,
                    53,
                    50,
                    43,
                    47,
                    52,
                    56,
                    52,
                    38,
                    44,
                    47,
                    44,
                    52,
                    51,
                    29,
                    41,
                    44,
                    43,
                    39,
                    51,
                    48,
                    53,
                    49,
                    50,
                    51,
                    45,
                    44,
                    40,
                    48,
                    43,
                    40,
                    45,
                    54,
                    18,
                    48,
                    49,
                    50,
                    42,
                    50,
                    52,
                    47,
                    40,
                    51,
                    51,
                    39,
                    52,
                    44,
                    41,
                    38,
                    48,
                    52,
                    55,
                    45,
                    45,
                    56,
                    52,
                    54,
                    29,
                    28,
                    48,
                    24,
                    55,
                    49,
                    39,
                    47,
                    51,
                    44,
                    41,
                    45,
                    44,
                    44,
                    44,
                    37,
                    45,
                    43,
                    56,
                    38,
                    47,
                    47,
                    43,
                    41,
                    54,
                    40,
                    51,
                    52,
                    49,
                    44,
                    47,
                    46,
                    48,
                    54,
                    51,
                    33,
                    50,
                    43,
                    48,
                    38,
                    57,
                    48,
                    38,
                    50,
                    43,
                    47,
                    42,
                    50,
                    51,
                    25,
                    15,
                    54,
                    43,
                    22,
                    49,
                    45,
                    48,
                    50,
                    49,
                    35,
                    43,
                    39,
                    39,
                    42,
                    46,
                    46,
                    40,
                    34,
                    42,
                    34,
                    29,
                    48,
                    41,
                    39,
                    54,
                    47,
                    49,
                    50,
                    44,
                    49
                ]
            },
            "faecher": [
                {
                    "code": "S03",
                    "titel": "Biologie, Anatomie",
                    "gruppe": "Vorklinische F\u00e4cher",
                    "ergebnisPunktzahl": 3,
                    "durchschnittsPunktzahl": 3.2,
                    "maximalPunktzahl": 4
                },
                {
                    "code": "S02",
                    "titel": "Chemie, Biochemie, Molekurlarbiologie",
                    "gruppe": "Vorklinische F\u00e4cher",
                    "ergebnisPunktzahl": 31,
                    "durchschnittsPunktzahl": 25.48,
                    "maximalPunktzahl": 34
                },
                {
                    "code": "S01",
                    "titel": "Physik, Physiologie",
                    "gruppe": "Vorklinische F\u00e4cher",
                    "ergebnisPunktzahl": 9,
                    "durchschnittsPunktzahl": 6.74,
                    "maximalPunktzahl": 9
                },
                {
                    "code": "F11",
                    "titel": "Innere Medizin",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisPunktzahl": 3,
                    "durchschnittsPunktzahl": 2.82,
                    "maximalPunktzahl": 3
                },
                {
                    "code": "F14",
                    "titel": "Neurologie",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisPunktzahl": 1,
                    "durchschnittsPunktzahl": 0.73,
                    "maximalPunktzahl": 1
                },
                {
                    "code": "F12",
                    "titel": "Kinderheilkunde",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisPunktzahl": 3,
                    "durchschnittsPunktzahl": 2.23,
                    "maximalPunktzahl": 3
                },
                {
                    "code": "F17",
                    "titel": "Pharmakologie, Toxikologie",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisPunktzahl": 3,
                    "durchschnittsPunktzahl": 2.21,
                    "maximalPunktzahl": 3
                },
                {
                    "code": "F09",
                    "titel": "Humangenetik",
                    "gruppe": "Klinische F\u00e4cher",
                    "ergebnisPunktzahl": 1,
                    "durchschnittsPunktzahl": 0.84,
                    "maximalPunktzahl": 1
                }
            ],
            "module": [
                {
                    "code": "M03",
                    "titel": "Modul 3",
                    "ergebnisPunktzahl": 0.89,
                    "durchschnittsPunktzahl": 0.73,
                    "maximalPunktzahl": 1
                },
                {
                    "code": "M04",
                    "titel": "Modul 4",
                    "ergebnisPunktzahl": 0.95,
                    "durchschnittsPunktzahl": 0.78,
                    "maximalPunktzahl": 1
                },
                {
                    "code": "M14",
                    "titel": "Modul 14",
                    "ergebnisPunktzahl": 1,
                    "durchschnittsPunktzahl": 0.56,
                    "maximalPunktzahl": 1
                },
                {
                    "code": "M02",
                    "titel": "Modul 2",
                    "ergebnisPunktzahl": 0.95,
                    "durchschnittsPunktzahl": 0.79,
                    "maximalPunktzahl": 1
                }
            ]
        }
    ]
}