name: Teams deployment message
on: 
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        branch=$(git symbolic-ref --short HEAD)
        author=$(git log -1 --pretty=format:'%an')
        branch="Branch: $branch\nAuthor: $author\n"
        curl -H 'Content-Type: application/json' -d "{\"text\": \"$branch\"}" 'https://charitede.webhook.office.com/webhookb2/05cdecbb-03b1-4cf7-934e-d6e1853711be@afe91939-923e-432c-bc66-cbc3ec18d02c/IncomingWebhook/1c6de73e11ab40c493f8ef6dcf337f85/ed938071-d67b-4ba0-82fc-652e714d5056'
