name: Teams deployment message
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        branch=$(git symbolic-ref --short HEAD)
        author=$(git log -1 --pretty=format:'%an')
        branch="Branch: $branch\nAuthor: $author\n"
        echo $branch
